/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PExpressionField.java
 *
 * Created on Sep 2, 2011, 9:45:27 AM
 */
package by.dak.profile.swing;

import by.dak.cutting.DialogShowers;
import by.dak.cutting.swing.DPanel;
import by.dak.swing.ActionsPanel;
import by.dak.swing.WindowCallback;

import javax.swing.*;

/**
 * @author admin
 */
public class PExpressionField extends DPanel
{

    private PExpressionEditor expressionEditor = new PExpressionEditor();
    private WindowCallback windowCallback = new WindowCallback();

    /**
     * Creates new form PExpressionField
     */
    public PExpressionField()
    {
        initComponents();
        buttonEdit.setAction(getAppActionMap().get("showEditor"));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        fieldExpression = new javax.swing.JTextField();
        buttonEdit = new javax.swing.JButton();

        fieldExpression.setName("fieldExpression"); // NOI18N

        buttonEdit.setText("jButton1");
        buttonEdit.setName("buttonEdit"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(fieldExpression, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getButtonEdit()
    {
        return buttonEdit;
    }

    public JTextField getFieldExpression()
    {
        return fieldExpression;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JTextField fieldExpression;
    // End of variables declaration//GEN-END:variables


    @org.jdesktop.application.Action
    public void showEditor()
    {
        ActionsPanel<PExpressionEditor> panel = new ActionsPanel<PExpressionEditor>();
        panel.setContentComponent(expressionEditor);
        panel.setActions("confirm");
        panel.setSourceActionMap(getAppActionMap());
        panel.init();
        expressionEditor.getTextArea().setText(getFieldExpression().getText());
        DialogShowers.showBy(panel, this, windowCallback, true);
    }

    @org.jdesktop.application.Action
    public void confirm()
    {
        getFieldExpression().setText(expressionEditor.getTextArea().getText());
        windowCallback.dispose();

    }
}

