-- refactoring tables
--ORDER_DETAIL
ALTER TABLE ORDER_FURNITURE RENAME TO ORDER_DETAIL;
alter table ORDER_DETAIL add DISCRIMINATOR VARCHAR(255) default 'OrderFurniture' not null;
ALTER TABLE ORDER_DETAIL ALTER COLUMN FK_FURN_ORDER_ITEM_ID RENAME TO ORDER_ITEM_ID;
ALTER TABLE ORDER_DETAIL ALTER COLUMN FK_TEXTURE_ID RENAME TO FURNITURE_CODE_ID;
ALTER TABLE ORDER_DETAIL ALTER COLUMN FK_BOARD_DEF_ID RENAME TO FURNITURE_TYPE_ID;
ALTER TABLE ORDER_DETAIL ALTER COLUMN FK_COMLEX_BOARD_DEF_ID RENAME TO COMLEX_BOARD_DEF_ID;
ALTER TABLE ORDER_DETAIL ALTER COLUMN FK_SECOND_BOARD_ID RENAME TO SECOND_BOARD_ID;
ALTER TABLE ORDER_DETAIL ALTER LENGTH bigint;
ALTER TABLE ORDER_DETAIL ALTER WIDTH bigint;
ALTER TABLE ORDER_DETAIL ALTER AMOUNT bigint;
ALTER TABLE ORDER_DETAIL ALTER ROTATABLE boolean;
ALTER TABLE ORDER_DETAIL ALTER FPRIMARY boolean;
ALTER TABLE ORDER_DETAIL ALTER FURNITURE_CODE_ID bigint;
ALTER TABLE ORDER_DETAIL ALTER FURNITURE_TYPE_ID bigint;
--Additional
ALTER table ORDER_DETAIL add TYPE VARCHAR(255);
ALTER table ORDER_DETAIL add PRICE DOUBLE;
--FurnitureLink
ALTER table ORDER_DETAIL add FURNITURE_ID bigint;
ALTER table ORDER_DETAIL add SIZE DOUBLE;

--ORDER_ITEM
ALTER TABLE FURN_ORDER_ITEM RENAME TO ORDER_ITEM;
ALTER TABLE ORDER_ITEM ALTER COLUMN FK_FURN_ORDER_ID RENAME TO ORDER_ID;

--STRIPS
ALTER TABLE STRIPS ALTER COLUMN FK_ORDER_ITEM_ID RENAME TO ORDER_ITEM_ID;
ALTER TABLE STRIPS ALTER COLUMN FK_TEXTURE_ID RENAME TO FURNITURE_CODE_ID;
ALTER TABLE STRIPS ALTER COLUMN FK_BOARD_DEF_ID RENAME TO FURNITURE_TYPE_ID;

--FURNITURE_TYPE
alter table FURNITURE_TYPE add DISCRIMINATOR varchar(255) DEFAULT 'FurnitureType' not null;
alter table FURNITURE_TYPE add TYPE varchar(255) null;
alter table FURNITURE_TYPE add HEIGHT bigint;
alter table FURNITURE_TYPE add THICKNESS bigint;
alter table FURNITURE_TYPE add DEFAULT_LENGTH bigint;
alter table FURNITURE_TYPE add DEFAULT_WIDTH bigint;
alter table FURNITURE_TYPE add SIMPLE_ID_1 bigint;
alter table FURNITURE_TYPE add SIMPLE_ID_2 bigint;

--FURNITURE_CODE
--texture
alter table FURNITURE_CODE add GROUP_IDENTIFIER varchar(255);
alter table FURNITURE_CODE add SURFACE varchar(255);
alter table FURNITURE_CODE add ROTATABLE boolean;
--service
alter table FURNITURE_CODE add SERVICE_TYPE VARCHAR(255);
-- alter table FURNITURE_CODE ALTER CODE VARCHAR(255);
-- alter table FURNITURE_CODE ALTER NAME VARCHAR(255);


-- FURNITURE
alter table FURNITURE ALTER SIZE DOUBLE;
alter table FURNITURE add LENGTH DOUBLE;
alter table FURNITURE add WIDTH bigint;
alter table FURNITURE add DISCRIMINATOR varchar(255) DEFAULT 'Furniture' not null;



-- update types

