/*
 * FrameElementlist.java
 *
 * Created on 27.jen 2006, 19:55
 */

package by.dak.cutting.cut.gui.cuttingApp;

import by.dak.cutting.cut.base.Element;
import by.dak.cutting.cut.graphics.Draw;

import java.awt.*;
import java.util.ArrayList;

/**
 * @author Peca
 */
public class FrameElementList extends javax.swing.JFrame
{
    private ArrayList<Element> elements = null;

    /**
     * Creates new form FrameElementlist
     */
    public FrameElementList()
    {
        initComponents();
    }

    private void paint()
    {
        if (elements == null) return;
        Graphics g = jPanel1.getGraphics();
        Graphics2D g2 = (Graphics2D) g;
        g.clearRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());

        int x = 20;
        int y = 10;
        Font f = new Font("serif", Font.BOLD, 15);
        for (int i = 0; i < elements.size(); i++)
        {
            Element el = elements.get(i);
            g.setColor(Draw.getColor(i));
            Draw.drawElement(el, x, y, g);
            g.setFont(f);
            g.drawString(String.valueOf(i), 2, y + 10);
            y += el.getHeight() + 10;
        }
    }

    public void setElements(ArrayList<Element> elements)
    {
        this.elements = elements;
        int h = 0;
        int w = 0;
        for (Element el : elements)
        {
            h += el.getHeight() + 10;
            if (w < el.getWidth()) w = el.getWidth();
        }
        h += 10;
        w += 20;
        jPanel1.setPreferredSize(new java.awt.Dimension(w, h));
        this.setSize(w, 500);
    }

    public void paint(Graphics g)
    {
        super.paint(g);
        paint();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <draw-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentMoved(java.awt.event.ComponentEvent evt)
            {
                jPanel1ComponentMoved(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(0, 381, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(0, 402, Short.MAX_VALUE)
        );
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </draw-fold>//GEN-END:initComponents

    private void jPanel1ComponentMoved(java.awt.event.ComponentEvent evt)
    {//GEN-FIRST:event_jPanel1ComponentMoved
        paint();
    }//GEN-LAST:event_jPanel1ComponentMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
