/*
 * To change this template, choose Tools | Templates
 * and open the template in the draw.
 */

/*
 * DictionaryTypePanel.java
 *
 * Created on 03.06.2009, 20:11:11
 */
package by.dak.cutting.swing.dictionaries;

import by.dak.cutting.swing.renderer.EntityListRenderer;
import by.dak.persistence.entities.predefined.MaterialType;
import org.jdesktop.beansbinding.*;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.swingbinding.SwingBindings;

import java.beans.Beans;
import java.util.Arrays;
import java.util.List;

/**
 * @author admin
 */
public class DictionaryTypePanel extends javax.swing.JPanel
{

    /**
     * Creates new form DictionaryTypePanel
     */
    public DictionaryTypePanel()
    {
        initComponents();
        if (!Beans.isDesignTime())
        {
            initEnvironment();
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelType = new javax.swing.JLabel();
        comboBoxType = new by.dak.cutting.swing.DComboBox();

        setName("DictionaryTypePanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(DictionaryTypePanel.class);
        labelType.setText(resourceMap.getString("labelType.text")); // NOI18N
        labelType.setName("labelType"); // NOI18N

        comboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        comboBoxType.setName("comboBoxType"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxType, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelType)
                                        .addComponent(comboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private by.dak.cutting.swing.DComboBox comboBoxType;
    private javax.swing.JLabel labelType;
    // End of variables declaration//GEN-END:variables

    private MaterialType materialType;

    private void initEnvironment()
    {
        comboBoxType.setRenderer(new EntityListRenderer<MaterialType>());

        BindingGroup bindingGroup = new BindingGroup();
        List<MaterialType> list = Arrays.asList(MaterialType.values());
        Binding binding = SwingBindings.createJComboBoxBinding(UpdateStrategy.READ_WRITE,
                list, comboBoxType);
        bindingGroup.addBinding(binding);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, comboBoxType,
                BeanProperty.create("selectedItem"),
                this, BeanProperty.create("materialType"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        bindingGroup.bind();
    }

    public MaterialType getMaterialType()
    {
        return materialType;
    }

    public void setMaterialType(MaterialType materialType)
    {
        MaterialType oldMaterialType = this.materialType;
        this.materialType = materialType;
        firePropertyChange("materialType", oldMaterialType, materialType);
    }

    @Override
    public void setEnabled(boolean enabled)
    {
        super.setEnabled(enabled);
        comboBoxType.setEnabled(enabled);
    }
}
