/*
 * To change this template, choose Tools | Templates
 * and open the template in the draw.
 */

/*
 * ProfileCompDefPanel.java
 *
 * Created on 9.9.2009, 16.25.28
 */

package by.dak.cutting.doors.profile.swing;

import by.dak.cutting.doors.profile.ProfileCompDef;
import by.dak.cutting.swing.BaseTabPanel;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.Bindings;

import java.beans.Beans;

/**
 * @author alkoyro
 */
public class ProfileCompDefPanel extends BaseTabPanel<ProfileCompDef>
{
    private final String regExp = "\\d{0,20}";

    /**
     * Creates new form ProfileCompDefPanel
     */
    public ProfileCompDefPanel()
    {
        initComponents();
        if (!Beans.isDesignTime())
        {
            initBinding();
        }
        textFieldIndent.setMask(regExp);
        textFieldLength.setMask(regExp);
        textFieldThickness.setMask(regExp);
        textFieldWidth.setMask(regExp);
    }


    protected void initBinding()
    {
        Binding bindingCode = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE,
                getValue(), BeanProperty.create("code"),
                textFieldCode, BeanProperty.create("text")

        );
        bindingCode.setSourceUnreadableValue(null);
        getBindingGroup().addBinding(bindingCode);

        Binding bindingThickness = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE,
                getValue(), BeanProperty.create("matThickness"),
                textFieldThickness, BeanProperty.create("text")

        );
        bindingThickness.setSourceUnreadableValue(null);
        getBindingGroup().addBinding(bindingThickness);

        Binding bindingWidth = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE,
                getValue(), BeanProperty.create("width"),
                textFieldWidth, BeanProperty.create("text")

        );
        bindingWidth.setSourceUnreadableValue(null);
        getBindingGroup().addBinding(bindingWidth);

        Binding bindingLength = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE,
                getValue(), BeanProperty.create("length"),
                textFieldLength, BeanProperty.create("text")

        );
        bindingLength.setSourceUnreadableValue(null);
        getBindingGroup().addBinding(bindingLength);

        Binding bindingIndent = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE,
                getValue(), BeanProperty.create("indent"),
                textFieldIndent, BeanProperty.create("text")

        );
        bindingIndent.setSourceUnreadableValue(null);
        getBindingGroup().addBinding(bindingIndent);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldCode = new by.dak.cutting.swing.component.MaskTextField();
        textFieldThickness = new by.dak.cutting.swing.component.MaskTextField();
        textFieldLength = new by.dak.cutting.swing.component.MaskTextField();
        textFieldWidth = new by.dak.cutting.swing.component.MaskTextField();
        textFieldIndent = new by.dak.cutting.swing.component.MaskTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(by.dak.cutting.CuttingApp.class).getContext().getResourceMap(ProfileCompDefPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        textFieldCode.setText(resourceMap.getString("textFieldCode.text")); // NOI18N
        textFieldCode.setName("textFieldCode"); // NOI18N

        textFieldThickness.setText(resourceMap.getString("textFieldThickness.text")); // NOI18N
        textFieldThickness.setName("textFieldThickness"); // NOI18N

        textFieldLength.setText(resourceMap.getString("textFieldLength.text")); // NOI18N
        textFieldLength.setName("textFieldLength"); // NOI18N

        textFieldWidth.setText(resourceMap.getString("textFieldWidth.text")); // NOI18N
        textFieldWidth.setName("textFieldWidth"); // NOI18N

        textFieldIndent.setText(resourceMap.getString("textFieldIndent.text")); // NOI18N
        textFieldIndent.setName("textFieldIndent"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldCode, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                        .addComponent(textFieldThickness, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                        .addComponent(textFieldLength, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                        .addComponent(textFieldWidth, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                        .addComponent(textFieldIndent, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(textFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(textFieldThickness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(textFieldLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(textFieldWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(textFieldIndent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private by.dak.cutting.swing.component.MaskTextField textFieldCode;
    private by.dak.cutting.swing.component.MaskTextField textFieldIndent;
    private by.dak.cutting.swing.component.MaskTextField textFieldLength;
    private by.dak.cutting.swing.component.MaskTextField textFieldThickness;
    private by.dak.cutting.swing.component.MaskTextField textFieldWidth;
    // End of variables declaration//GEN-END:variables
}
