create table COLOR (ID bigint generated by default as identity,
NAME VARCHAR(255) not null,
CODE bigint not null,
SURFACE VARCHAR(255),
ROTATABLE BOOLEAN,
constraint PK_COLOR primary key (ID) ,
unique (NAME, CODE, SURFACE, ROTATABLE)
);
