create table DELIVERY (ID bigint generated by default as identity,
DELIVERY_DATE date not null,
MAT_TYPE VARCHAR(255) DEFAULT 'border' not null,
PROVIDER_ID bigint not null);

alter table DELIVERY add constraint PROVIDER_DELIVERY foreign key (PROVIDER_ID) references PROVIDER;
