drop table SERVICE CASCADE;

create table SERVICE (
ID bigint generated by default as identity,
SERVICE_TYPE VARCHAR(255) not null,
constraint PK_SERVICE primary key (ID));

alter table SERVICE add constraint SERVICE_UNIQUE unique (SERVICE_TYPE);
