ALTER TABLE FURNITURE_DEF ALTER COLUMN TYPE SET null;
ALTER TABLE FURNITURE_DEF ADD COLUMN DEFAULT_LENGTH bigint;
ALTER TABLE FURNITURE_DEF ADD COLUMN DEFAULT_WIDTH bigint;
UPDATE FURNITURE_DEF set DEFAULT_LENGTH = 2800 , DEFAULT_WIDTH = 2070;
alter table ORDER_FURNITURE drop constraint SECOND_FURNITURE_ITEM;

