create table PROVIDER (
ID bigint generated by default as identity,
SHORT_NAME varchar(255) not null,
NAME varchar(255) not null,
ADDRESS varchar(255),
PHONE_NUMBER varchar(255),
FAX_NUMBER varchar(255),
EMAIL_ADDRESS varchar(255),
OFFICIAL_SITE varchar(255),
constraint PK_PROVIDER primary key (ID),
unique (SHORT_NAME),
unique (NAME));
