--price update
alter table PRICE add column PRICEAWARE_ID bigint null;
alter table PRICE add column PRICED_ID bigint null;
--texture update
ALTER TABLE TEXTURE ALTER COLUMN NAME_ENG SET NULL;
ALTER TABLE TEXTURE ALTER COLUMN SURFACE SET NULL;
--create table SERVICE
create table SERVICE (
ID bigint generated by default as identity,
NAME VARCHAR(255) not null,
MATERIAL_TYPE VARCHAR(255) not null,
constraint PK_SERVICE primary key (ID));

