/*
 * SegmentTest2.java
 *
 * Created on 30. jen 2007, 16:04
 */

package by.dak.cutting.cut.test;

import by.dak.cutting.cut.base.Element;
import by.dak.cutting.cut.common.Common;
import by.dak.cutting.cut.guillotine.GuillotineTreeCutter;
import by.dak.cutting.cut.guillotine.Segment;
import by.dak.cutting.cut.guillotine.SegmentPainter;

import javax.swing.*;
import java.awt.*;

/**
 * @author Peca
 */
public class SegmentTest2 extends javax.swing.JFrame
{

    private Segment segment;
    private Segment segment2;

    public SegmentTest2()
    {
        initComponents();
        segment = new Segment();
        segment2 = new Segment();
        segment.setWidth(200);
        segment.setFixedWidth(true);
        segment2.setLength(200);
        segment2.setFixedLength(true);

        GuillotineTreeCutter cutter = new GuillotineTreeCutter();
        for (int i = 0; i < 50; i++)
        {
            Element el = new Element(Common.nextInt(50) + 20, Common.nextInt(50) + 20, i);
            cutter.cut(segment2, el, 2, 30, false);
            if (i == 2) segment2.setFixedWidth(true);
        }

        segment.addSegment(segment2);

        JPanel panel;
        panel = new JPanel()
        {
            public void paint(Graphics g)
            {
                SegmentPainter.draw(g, segment);
            }
        };
        jPanel1.add(panel);
    }


    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("jButton1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                                .add(18, 18, 18)
                                                .add(jButton1))
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 289, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                                .add(jButton1)
                                .add(29, 29, 29))
        );

        pack();
    }// </draw-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SegmentTest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
