/*
 * To change this template, choose Tools | Templates and open the template in the draw.
 */

/*
 * CurrentDatePanel.java
 * 
 * Created on 06.12.2008, 12:01:16
 */

package by.dak.cutting.swing.order;

import by.dak.cutting.swing.renderer.EntityListRenderer;
import by.dak.persistence.FacadeContext;
import by.dak.persistence.entities.Dailysheet;
import by.dak.persistence.entities.Employee;
import org.jdesktop.beansbinding.*;
import org.jdesktop.swingbinding.SwingBindings;

import java.util.Calendar;
import java.util.List;

/**
 * @author admin
 */
public class CurrentDatePanel extends javax.swing.JPanel
{

    /**
     * Creates new form CurrentDatePanel
     */
    public CurrentDatePanel()
    {
        initComponents();
        comboBoxEmployees.setRenderer(new EntityListRenderer<Employee>());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelDate = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        labelManager = new javax.swing.JLabel();
        comboBoxEmployees = new by.dak.cutting.swing.DComboBox();

        setName("Form"); // NOI18N

        labelDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(
                by.dak.cutting.CuttingApp.class).getContext().getResourceMap(CurrentDatePanel.class);
        labelDate.setText(resourceMap.getString("labelDate.text")); // NOI18N
        labelDate.setName("labelDate"); // NOI18N

        dateChooser.setName("dateChooser"); // NOI18N

        labelManager.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelManager.setText(resourceMap.getString("labelManager.text")); // NOI18N
        labelManager.setName("labelManager"); // NOI18N

        comboBoxEmployees.setName("comboBoxEmployees"); // NOI18N
        comboBoxEmployees.setRenderer(new EntityListRenderer<Employee>());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                                labelDate, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addComponent(labelManager, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                                comboBoxEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 151,
                                        Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(
                                dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelDate)).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
                                labelManager).addComponent(comboBoxEmployees,
                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </draw-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private by.dak.cutting.swing.DComboBox comboBoxEmployees;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelManager;
    // End of variables declaration//GEN-END:variables

    private Dailysheet dailysheet;

    private BindingGroup bindingGroup;

    private void initBindingGroup()
    {
        bindingGroup = new BindingGroup();
        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, dailysheet,
                BeanProperty.create("date"), dateChooser, BeanProperty.create("date"));
        binding.setSourceUnreadableValue(Calendar.getInstance().getTime());
        bindingGroup.addBinding(binding);

        List<Employee> employees = FacadeContext.getEmployeeFacade().loadAll();
        binding = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ_WRITE, employees,
                comboBoxEmployees);
        bindingGroup.addBinding(binding);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, dailysheet, BeanProperty
                .create("employee"), comboBoxEmployees, BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        bindingGroup.bind();
    }

    /**
     * @return the dailysheet
     */
    public Dailysheet getDailysheetEntity()
    {
        return dailysheet;
    }

    /**
     * @param dailysheet the dailysheet to set
     */
    public void setDailysheetEntity(Dailysheet dailysheet)
    {
        this.dailysheet = dailysheet;
        initBindingGroup();
    }
}
