/*
 * To change this template, choose Tools | Templates
 * and open the template in the draw.
 */

/*
 * CutoffEditorPanel.java
 *
 * Created on 19.04.2009, 14:06:03
 */

package by.dak.cutting.swing.order.cellcomponents.editors.cuttoff;

import by.dak.cutting.swing.order.data.Cutoff;

import javax.swing.*;
import java.awt.*;
import java.beans.Beans;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 * @author admin
 */
public class CutoffEditorPanel extends javax.swing.JPanel {
	private Dimension element;
	private Cutoff cutoff;

	private CutoffPanel cutoffPanel = new CutoffPanel();
	private Cutoff2DPanel cutoff2DPanel = new Cutoff2DPanel();

	/**
	 * Creates new form CutoffEditorPanel
	 */
	public CutoffEditorPanel() {
		initComponents();
		initEnvironment();
	}

	private void initEnvironment() {
		if (!Beans.isDesignTime()) {

			jSplitPane1.setRightComponent(getCutoff2DPanel());
			jSplitPane1.setLeftComponent(getCutoffPanel());

			getCutoff2DPanel().getPropertySupport().addPropertyChangeListener(new PropertyChangeListener() {
				@Override
				public void propertyChange(PropertyChangeEvent evt) {
					getCutoffPanel().setCutoff((Cutoff) evt.getNewValue());
				}
			});
			getCutoffPanel().getPropertySupport().addPropertyChangeListener(new PropertyChangeListener() {
				@Override
				public void propertyChange(PropertyChangeEvent evt) {
					getCutoff2DPanel().setCutoff((Cutoff) evt.getNewValue());
				}
			});
		}
	}


	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jSplitPane1 = new javax.swing.JSplitPane();
		buttonOk = new javax.swing.JButton();

		jSplitPane1.setName("jSplitPane1"); // NOI18N

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(CutoffEditorPanel.class);
		buttonOk.setText(resourceMap.getString("buttonOk.text")); // NOI18N
		buttonOk.setName("buttonOk"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addContainerGap(283, Short.MAX_VALUE)
								.addComponent(buttonOk)
								.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap())
		);
	}// </draw-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonOk;
	private javax.swing.JSplitPane jSplitPane1;
	// End of variables declaration//GEN-END:variables


	public JButton getButtonOk() {
		return buttonOk;
	}

	public Dimension getElement() {
		return element;
	}

	public void setElement(Dimension element) {
		this.element = element;

		getCutoff2DPanel().setElement(element);

		Runnable runnable = new Runnable() {
			@Override
			public void run() {
				jSplitPane1.setOrientation(getElement().getWidth() > getElement().getHeight() ? JSplitPane.VERTICAL_SPLIT : JSplitPane.HORIZONTAL_SPLIT);
				revalidate();
			}
		};
		SwingUtilities.invokeLater(runnable);
	}

	public Cutoff getCutoff() {
		return cutoff;
	}

	public void setCutoff(Cutoff cutoff) {
		this.cutoff = cutoff;
		getCutoff2DPanel().setCutoff(cutoff);
		getCutoffPanel().setCutoff(cutoff);
	}


	public CutoffPanel getCutoffPanel() {
		return cutoffPanel;
	}

	public Cutoff2DPanel getCutoff2DPanel() {
		return cutoff2DPanel;
	}
}
