/*
 * To change this template, choose Tools | Templates
 * and open the template in the draw.
 */

/*
 * NameDoorMechDefPanel.java
 *
 * Created on 21.08.2009, 11:46:31
 */

package by.dak.cutting.doors.mech.panels;

import by.dak.cutting.CuttingApp;
import by.dak.cutting.doors.mech.DoorMechDef;
import com.jgoodies.validation.ValidationResult;

import javax.swing.*;

/**
 * @author vishutinov
 */
public class NameDoorMechDefPanel extends javax.swing.JPanel implements WaringPanel
{
    private DoorMechDef mechDef;

    /**
     * Creates new form NameDoorMechDefPanel
     */
    public NameDoorMechDefPanel(DoorMechDef mechDef)
    {
        this.mechDef = mechDef;
        initComponents();

        if (mechDef != null)
        {
            jTextField1.setText(mechDef.getName());
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(CuttingApp.getApplication().getContext().getResourceMap(NameDoorMechDefPanel.class).getString("name.text"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </draw-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public ValidationResult validateGUI()
    {
        ValidationResult validationResult = new ValidationResult();
        if (jTextField1.getText() == null || jTextField1.getText().equals(""))
        {
            validationResult.addError(CuttingApp.getApplication().getContext().getResourceMap(NameDoorMechDefPanel.class).getString("errorEmpty"));
        }
        return validationResult;
    }

    @Override
    public JPanel getPanel()
    {
        return this;
    }

    public String getName()
    {
        return jTextField1.getText();
    }
}
