/*
 * To change this template, choose Tools | Templates
 * and open the template in the draw.
 */

/*
 * MultiSelectComponent.java
 *
 * Created on 13.05.2009, 18:16:53
 */
package by.dak.swing;

import org.jdesktop.application.ResourceMap;

import javax.swing.*;
import java.beans.Beans;
import java.beans.PropertyChangeListener;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 * @author admin
 */
public class MultiSelectComponent extends javax.swing.JPanel
{

    private ListCellRenderer sourceRenderer;

    private ListCellRenderer targetRenderer;

    /**
     * Creates new form MultiSelectComponent
     */
    public MultiSelectComponent()
    {
        initComponents();
        if (!Beans.isDesignTime())
        {
            init();
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonAddAll = new javax.swing.JButton();
        jButtonRemoveAll = new javax.swing.JButton();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jideScrollPane2 = new com.jidesoft.swing.JideScrollPane();
        checkBoxList2 = new com.jidesoft.swing.CheckBoxList();
        jXTitledPanel2 = new org.jdesktop.swingx.JXTitledPanel();
        jideScrollPane1 = new com.jidesoft.swing.JideScrollPane();
        checkBoxList1 = new com.jidesoft.swing.CheckBoxList();

        setName("Form"); // NOI18N

        jXPanel2.setName("jXPanel2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(MultiSelectComponent.class);
        jButtonAdd.setText(resourceMap.getString("jButtonAdd.text")); // NOI18N
        jButtonAdd.setName("jButtonAdd"); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonRemove.setText(resourceMap.getString("jButtonRemove.text")); // NOI18N
        jButtonRemove.setName("jButtonRemove"); // NOI18N
        jButtonRemove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonAddAll.setText(resourceMap.getString("jButtonAddAll.text")); // NOI18N
        jButtonAddAll.setName("jButtonAddAll"); // NOI18N
        jButtonAddAll.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddAllActionPerformed(evt);
            }
        });

        jButtonRemoveAll.setText(resourceMap.getString("jButtonRemoveAll.text")); // NOI18N
        jButtonRemoveAll.setName("jButtonRemoveAll"); // NOI18N
        jButtonRemoveAll.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRemoveAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel2Layout = new javax.swing.GroupLayout(jXPanel2);
        jXPanel2.setLayout(jXPanel2Layout);
        jXPanel2Layout.setHorizontalGroup(
                jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jXPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(jButtonRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(jButtonAddAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(jButtonRemoveAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
        );
        jXPanel2Layout.setVerticalGroup(
                jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jXPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoveAll)
                        .addContainerGap(228, Short.MAX_VALUE))
        );

        jXTitledPanel1.setTitle(resourceMap.getString("jXTitledPanel1.title")); // NOI18N
        jXTitledPanel1.setName("jXTitledPanel1"); // NOI18N

        jideScrollPane2.setName("jideScrollPane2"); // NOI18N

        checkBoxList2.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize()
            {
                return strings.length;
            }

            public Object getElementAt(int i)
            {
                return strings[i];
            }
        });
        checkBoxList2.setName("checkBoxList2"); // NOI18N
        jideScrollPane2.setViewportView(checkBoxList2);

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
                jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jideScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );
        jXTitledPanel1Layout.setVerticalGroup(
                jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jideScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        jXTitledPanel2.setTitle(resourceMap.getString("jXTitledPanel2.title")); // NOI18N
        jXTitledPanel2.setName("jXTitledPanel2"); // NOI18N

        jideScrollPane1.setName("jideScrollPane1"); // NOI18N

        checkBoxList1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize()
            {
                return strings.length;
            }

            public Object getElementAt(int i)
            {
                return strings[i];
            }
        });
        checkBoxList1.setName("checkBoxList1"); // NOI18N
        jideScrollPane1.setViewportView(checkBoxList1);

        javax.swing.GroupLayout jXTitledPanel2Layout = new javax.swing.GroupLayout(jXTitledPanel2.getContentContainer());
        jXTitledPanel2.getContentContainer().setLayout(jXTitledPanel2Layout);
        jXTitledPanel2Layout.setHorizontalGroup(
                jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jideScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        jXTitledPanel2Layout.setVerticalGroup(
                jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jideScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jXTitledPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jXPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(jXTitledPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </draw-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddActionPerformed
    {//GEN-HEADEREND:event_jButtonAddActionPerformed
        multiSelectComponentController.addSelectedElements(Arrays.asList(checkBoxList1.getCheckBoxListSelectedValues()));
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRemoveActionPerformed
    {//GEN-HEADEREND:event_jButtonRemoveActionPerformed
        multiSelectComponentController.removeSelectedElements(Arrays.asList(checkBoxList2.getCheckBoxListSelectedValues()));
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonAddAllActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddAllActionPerformed
    {//GEN-HEADEREND:event_jButtonAddAllActionPerformed
        checkBoxList1.selectAll();
        multiSelectComponentController.addSelectedElements(Arrays.asList(checkBoxList1.getCheckBoxListSelectedValues()));
    }//GEN-LAST:event_jButtonAddAllActionPerformed

    private void jButtonRemoveAllActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRemoveAllActionPerformed
    {//GEN-HEADEREND:event_jButtonRemoveAllActionPerformed
        checkBoxList2.selectAll();
        multiSelectComponentController.removeSelectedElements(Arrays.asList(checkBoxList2.getCheckBoxListSelectedValues()));
    }//GEN-LAST:event_jButtonRemoveAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jidesoft.swing.CheckBoxList checkBoxList1;
    private com.jidesoft.swing.CheckBoxList checkBoxList2;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddAll;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonRemoveAll;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel2;
    private com.jidesoft.swing.JideScrollPane jideScrollPane1;
    private com.jidesoft.swing.JideScrollPane jideScrollPane2;
    // End of variables declaration//GEN-END:variables

    private MultiSelectComponentController multiSelectComponentController;

    private ResourceMap resourceMap;

    private void init()
    {
        multiSelectComponentController = new MultiSelectComponentController();
        multiSelectComponentController.setMultiSelectComponent(this);
    }

    JList getSourceList()
    {
        return checkBoxList1;
    }

    JList getTargetList()
    {
        return checkBoxList2;
    }

    public void setElements(List elements)
    {
        multiSelectComponentController.setElements(elements);
    }

    public List getElements()
    {
        return multiSelectComponentController.getElements();
    }

    public List getSelectedElements()
    {
        return multiSelectComponentController.getSelectedElements();
    }

    public void setSelectedElements(List elements)
    {
        multiSelectComponentController.setSelectedElements(elements);
    }

    public void setComparator(Comparator comparator)
    {
        multiSelectComponentController.setComparator(comparator);
    }

    public Comparator getComparator()
    {
        return multiSelectComponentController.getComparator();
    }

    public void setSourceRenderer(ListCellRenderer renderer)
    {
        this.sourceRenderer = renderer;
        getSourceList().setCellRenderer(this.sourceRenderer);
        getTargetList().setCellRenderer(getTargetRenderer() == null ? this.sourceRenderer : getTargetRenderer());
    }

    public ListCellRenderer getSourceRenderer()
    {
        return this.sourceRenderer;
    }

    public ListCellRenderer getTargetRenderer()
    {
        return targetRenderer;
    }

    public void setTargetRenderer(ListCellRenderer targetRenderer)
    {
        this.targetRenderer = targetRenderer;
        getTargetList().setCellRenderer(getTargetRenderer() == null ? getSourceRenderer() : getTargetRenderer());
    }

    public void addSelectedElementListener(PropertyChangeListener listener)
    {
        multiSelectComponentController.getPropertyChangeSupport().addPropertyChangeListener("selectedElements", listener);
    }

    public void removeSelectedElementListener(PropertyChangeListener listener)
    {
        multiSelectComponentController.getPropertyChangeSupport().removePropertyChangeListener("selectedElements", listener);
    }

    public ResourceMap getResourceMap()
    {
        return resourceMap;
    }

    public void setResourceMap(ResourceMap resourceMap)
    {
        this.resourceMap = resourceMap;
        jButtonAdd.setText(resourceMap.getString("MultiSelectComponent.jButtonAdd.text")); // NOI18N
        jButtonAddAll.setText(resourceMap.getString("MultiSelectComponent.jButtonAddAll.text")); // NOI18N
        jButtonRemoveAll.setText(resourceMap.getString("MultiSelectComponent.jButtonRemoveAll.text")); // NOI18N
        jButtonRemove.setText(resourceMap.getString("MultiSelectComponent.jButtonRemove.text")); // NOI18N
        jXTitledPanel1.setTitle(resourceMap.getString("MultiSelectComponent.jXTitledPanel1.title")); // NOI18N
        jXTitledPanel2.setTitle(resourceMap.getString("MultiSelectComponent.jXTitledPanel2.title")); // NOI18N
    }

    public SourceTargetConverter getSourceTargetConverter()
    {
        return multiSelectComponentController.getSourceTargetConverter();
    }

    public void setSourceTargetConverter(SourceTargetConverter sourceTargetConverter)
    {
        multiSelectComponentController.setSourceTargetConverter(sourceTargetConverter);
    }
}
