alter TABLE ORDER_ITEM ADD DESCRIPTION VARCHAR(2147483647);
alter TABLE ORDER_ITEM ADD FILE_UUID VARCHAR(255);

alter TABLE FURN_ORDER ADD FILE_UUID VARCHAR(255);
alter TABLE FURN_ORDER ADD DISCRIMINATOR VARCHAR(255);
update FURN_ORDER set DISCRIMINATOR = 'Order';
alter TABLE FURN_ORDER alter column DESCRIPTION VARCHAR(2147483647);
alter TABLE FURN_ORDER ADD CATEGORY_ID  BIGINT;
