/*
 * To change this template, choose Tools | Templates
 * and open the template in the draw.
 */

/*
 * GluiengDialog.java
 *
 * Created on 25.8.2009, 10.42.26
 */

package by.dak.cutting.swing.order.cellcomponents.editors.milling.glueing;

import by.dak.persistence.entities.BorderDefEntity;
import by.dak.persistence.entities.TextureEntity;
import com.jgoodies.validation.ValidationResult;

import java.awt.*;
import java.util.List;

/**
 * @author alkoyro
 */
public class GluiengDialog extends javax.swing.JDialog
{
    /**
     * Creates new form GluiengDialog
     */
    public GluiengDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    public GluiengDialog(Dialog owner, boolean modal)
    {
        super(owner, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        gluiengPanel = new by.dak.cutting.swing.order.cellcomponents.editors.milling.glueing.GluiengPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        gluiengPanel.setName("gluiengPanel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gluiengPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gluiengPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </draw-fold>//GEN-END:initComponents


    public Gluieng getGluieng()
    {
        return gluiengPanel.getGluieng();
    }

    public void setGluieng(Gluieng gluieng)
    {
        gluiengPanel.setGluieng(gluieng);
    }

    public void setTextures(List<TextureEntity> listTextures)
    {
        gluiengPanel.setTextures(listTextures);
    }

    public void setBorderDefs(List<BorderDefEntity> listBorderDefs)
    {
        gluiengPanel.setBorderDefs(listBorderDefs);
    }

    public ValidationResult getValidationResult()
    {
        return gluiengPanel.getValidationResult();
    }

    @Override
    public void dispose()
    {
        super.dispose();
    }

    public GluiengPanel getGluiengPanel()
    {
        return gluiengPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private by.dak.cutting.swing.order.cellcomponents.editors.milling.glueing.GluiengPanel gluiengPanel;
    // End of variables declaration//GEN-END:variables

}
