-- ----------------------------------------------------------------------
-- MySQL Migration Toolkit
-- SQL Create Script
-- ----------------------------------------------------------------------

SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `PUBLIC`
  CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `PUBLIC`;
-- -------------------------------------
-- Tables

DROP TABLE IF EXISTS `PUBLIC`.`MANUFACTURER`;
CREATE TABLE `PUBLIC`.`MANUFACTURER` (
  `ID` BIGINT(64) NOT NULL,
  `SHORT_NAME` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(255) NULL,
  `PHONE_NUMBER` VARCHAR(255) NULL,
  `FAX_NUMBER` VARCHAR(255) NULL,
  `EMAIL_ADDRESS` VARCHAR(255) NULL,
  `OFFICIAL_SITE` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_MANUFACTURER_10031` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10029_10032` (`SHORT_NAME`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10030_10033` (`NAME`)
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`CUTTER`;
CREATE TABLE `PUBLIC`.`CUTTER` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SAWCUT_WIDTH` BIGINT(64) NOT NULL,
  `CUT_SIZE_LEFT` BIGINT(64) NOT NULL,
  `CUT_SIZE_RIGHT` BIGINT(64) NOT NULL,
  `CUT_SIZE_BOTTOM` BIGINT(64) NOT NULL,
  `CUT_SIZE_TOP` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_CUTTER_10042` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10041_10043` (`NAME`)
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`CUSTOMER`;
CREATE TABLE `PUBLIC`.`CUSTOMER` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(255) NULL,
  `PHONE_NUMBER` VARCHAR(255) NULL,
  `PHONE_NUMBER1` VARCHAR(255) NULL,
  `FAX_NUMBER` VARCHAR(255) NULL,
  `EMAIL_ADDRESS` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_CUSTOMER_10047` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10046_10048` (`NAME`)
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`FURN_ORDER`;
CREATE TABLE `PUBLIC`.`FURN_ORDER` (
  `ID` BIGINT(64) NOT NULL,
  `COST` DOUBLE NULL,
  `ORDER_NUMBER` BIGINT(64) NOT NULL,
  `READY_DATE` DATE NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` LONGTEXT NULL,
  `FK_CREATED_DAILY_SHEET_ID` BIGINT(64) NOT NULL,
  `FK_WORKED_DAILY_SHEET_ID` BIGINT(64) NULL,
  `FK_CUSTOMER_ID` BIGINT(64) NOT NULL,
  `FK_DESIGNER_ID` BIGINT(64) NULL,
  `STATUS` VARCHAR(255) NOT NULL DEFAULT 'design',
  `DILER_ORDER_ID` BIGINT(64) NULL,
  `FILE_UUID` VARCHAR(255) NULL,
  `DISCRIMINATOR` VARCHAR(255) NULL,
  `CATEGORY_ID` BIGINT(64) NULL,
  `SALE_FACTOR` DOUBLE NULL,
  `SALE_PRICE` DOUBLE NULL,
  `DIALER_COST` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_ORDER_10055` (`ID`),
  INDEX `SYS_IDX_10056` (`FK_CUSTOMER_ID`),
  INDEX `SYS_IDX_10296` (`FK_DESIGNER_ID`),
  INDEX `SYS_IDX_10298` (`FK_WORKED_DAILY_SHEET_ID`),
  INDEX `SYS_IDX_10300` (`FK_CREATED_DAILY_SHEET_ID`),
  INDEX `SYS_IDX_10302` (`DILER_ORDER_ID`),
  INDEX `SYS_IDX_10304` (`CATEGORY_ID`),
  CONSTRAINT `FURN_ORDER_CATEGORY` FOREIGN KEY `FURN_ORDER_CATEGORY` (`CATEGORY_ID`)
    REFERENCES `PUBLIC`.`CATEGORY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CUSTOMER_ORDER` FOREIGN KEY `CUSTOMER_ORDER` (`FK_CUSTOMER_ID`)
    REFERENCES `PUBLIC`.`CUSTOMER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `WORKED_DAILY_SHEET` FOREIGN KEY `WORKED_DAILY_SHEET` (`FK_WORKED_DAILY_SHEET_ID`)
    REFERENCES `PUBLIC`.`DAILY_SHEET` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CREATED_DAILY_SHEET` FOREIGN KEY `CREATED_DAILY_SHEET` (`FK_CREATED_DAILY_SHEET_ID`)
    REFERENCES `PUBLIC`.`DAILY_SHEET` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DESIGNER_ORDER` FOREIGN KEY `DESIGNER_ORDER` (`FK_DESIGNER_ID`)
    REFERENCES `PUBLIC`.`DESIGNER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DILER_ORDER_CONSTR` FOREIGN KEY `DILER_ORDER_CONSTR` (`DILER_ORDER_ID`)
    REFERENCES `PUBLIC`.`DILER_ORDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`ORDER_DETAIL`;
CREATE TABLE `PUBLIC`.`ORDER_DETAIL` (
  `ID` BIGINT(64) NOT NULL,
  `NUMBER` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `LENGTH` BIGINT(64) NULL,
  `WIDTH` BIGINT(64) NULL,
  `AMOUNT` BIGINT(64) NULL,
  `ROTATABLE` BOOLEAN NULL,
  `GLUEING` LONGTEXT NULL,
  `MILLING` LONGTEXT NULL,
  `GROOVE` LONGTEXT NULL,
  `ANGLE45` LONGTEXT NULL,
  `DRILLING` LONGTEXT NULL,
  `CUTOFF` LONGTEXT NULL,
  `FURNITURE_TYPE_ID` BIGINT(64) NULL,
  `FURNITURE_CODE_ID` BIGINT(64) NULL,
  `COMLEX_BOARD_DEF_ID` BIGINT(64) NULL,
  `SECOND_BOARD_ID` BIGINT(64) NULL,
  `ORDER_ITEM_ID` BIGINT(64) NULL,
  `FPRIMARY` BOOLEAN NULL,
  `DISCRIMINATOR` VARCHAR(255) NOT NULL DEFAULT 'OrderFurniture',
  `TYPE` VARCHAR(255) NULL,
  `PRICE` DOUBLE NULL,
  `FURNITURE_ID` BIGINT(64) NULL,
  `SIZE` DOUBLE NULL,
  `SIDE` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_ORDER_DETAIL_10062` (`ID`),
  INDEX `SYS_IDX_10063` (`SECOND_BOARD_ID`),
  INDEX `SYS_IDX_10306` (`FURNITURE_ID`),
  INDEX `SYS_IDX_10308` (`COMLEX_BOARD_DEF_ID`),
  INDEX `SYS_IDX_10310` (`ORDER_ITEM_ID`),
  INDEX `SYS_IDX_10312` (`FURNITURE_TYPE_ID`),
  INDEX `SYS_IDX_10314` (`FURNITURE_CODE_ID`),
  CONSTRAINT `FURNITURE_FURNITURE_LINK` FOREIGN KEY `FURNITURE_FURNITURE_LINK` (`FURNITURE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORDER_DETAIL_FURNITURE_CODE` FOREIGN KEY `ORDER_DETAIL_FURNITURE_CODE` (`FURNITURE_CODE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_CODE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `COMPLEX_DEF_FURN_TYPE` FOREIGN KEY `COMPLEX_DEF_FURN_TYPE` (`COMLEX_BOARD_DEF_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORDER_DETAIL_FURNITURE_TYPE` FOREIGN KEY `ORDER_DETAIL_FURNITURE_TYPE` (`FURNITURE_TYPE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SECOND_BOARD` FOREIGN KEY `SECOND_BOARD` (`SECOND_BOARD_ID`)
    REFERENCES `PUBLIC`.`ORDER_DETAIL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORDER_DETAIL_ORDER_ITEM` FOREIGN KEY `ORDER_DETAIL_ORDER_ITEM` (`ORDER_ITEM_ID`)
    REFERENCES `PUBLIC`.`ORDER_ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`PRICE`;
CREATE TABLE `PUBLIC`.`PRICE` (
  `ID` BIGINT(64) NOT NULL,
  `PRICEAWARE_ID` BIGINT(64) NOT NULL,
  `PRICED_ID` BIGINT(64) NOT NULL,
  `PRICE` DOUBLE NOT NULL,
  `PRICE_DEALER` DOUBLE NOT NULL,
  `PRICE_FAKTOR` DOUBLE NOT NULL,
  `CURRENCY_TYPE` VARCHAR(255) NOT NULL DEFAULT 'USD',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_PRICE_10072` (`ID`),
  INDEX `SYS_IDX_10316` (`PRICED_ID`),
  INDEX `SYS_IDX_10318` (`PRICEAWARE_ID`),
  CONSTRAINT `PRICE_FURNITURE_CODE` FOREIGN KEY `PRICE_FURNITURE_CODE` (`PRICED_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_CODE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PRICE_FURNITURE_TYPE` FOREIGN KEY `PRICE_FURNITURE_TYPE` (`PRICEAWARE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`ORDER_ITEM`;
CREATE TABLE `PUBLIC`.`ORDER_ITEM` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `ORDER_ID` BIGINT(64) NULL,
  `TYPE` VARCHAR(255) NOT NULL DEFAULT 'first',
  `NUMBER` BIGINT(64) NOT NULL DEFAULT 1,
  `AMOUNT` BIGINT(64) NOT NULL DEFAULT 1,
  `LENGTH` DOUBLE NULL,
  `WIDTH` DOUBLE NULL,
  `DISCRIMINATOR` VARCHAR(255) NOT NULL DEFAULT 'OrderItem',
  `DESCRIPTION` LONGTEXT NULL,
  `FILE_UUID` VARCHAR(255) NULL,
  `DESIGN` LONGTEXT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_ORDER_ITEM_10079` (`ID`),
  INDEX `SYS_IDX_10080` (`ORDER_ID`),
  CONSTRAINT `ORDER_ITEM_ORDER` FOREIGN KEY `ORDER_ITEM_ORDER` (`ORDER_ID`)
    REFERENCES `PUBLIC`.`FURN_ORDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`EMPLOYEE`;
CREATE TABLE `PUBLIC`.`EMPLOYEE` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SURNAME` VARCHAR(255) NOT NULL,
  `FK_DEPARTMENT_ID` BIGINT(64) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `USERNAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_EMPLOYEE_10088` (`ID`),
  UNIQUE INDEX `SYS_IDX_EMPLOYEE_NAME_SURNAME_1` (`NAME`, `SURNAME`),
  INDEX `SYS_IDX_10320` (`FK_DEPARTMENT_ID`),
  CONSTRAINT `DEPART_EMPL` FOREIGN KEY `DEPART_EMPL` (`FK_DEPARTMENT_ID`)
    REFERENCES `PUBLIC`.`DEPARTMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`DEPARTMENT`;
CREATE TABLE `PUBLIC`.`DEPARTMENT` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_DEPARTMENT_10092` (`ID`)
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`SHIFT`;
CREATE TABLE `PUBLIC`.`SHIFT` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `FK_DEPARTMENT_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_SHIFT_10097` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10096_10098` (`NAME`),
  INDEX `SYS_IDX_10099` (`FK_DEPARTMENT_ID`),
  CONSTRAINT `DEPART_SHIFT` FOREIGN KEY `DEPART_SHIFT` (`FK_DEPARTMENT_ID`)
    REFERENCES `PUBLIC`.`DEPARTMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`SHIFT_EMPLOYEE`;
CREATE TABLE `PUBLIC`.`SHIFT_EMPLOYEE` (
  `ID` BIGINT(64) NOT NULL,
  `FK_SHIFT_ID` BIGINT(64) NOT NULL,
  `FK_EMPLOYEE_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_SHIFT_EMPL_10104` (`ID`),
  INDEX `SYS_IDX_10105` (`FK_EMPLOYEE_ID`),
  INDEX `SYS_IDX_10107` (`FK_SHIFT_ID`),
  CONSTRAINT `EMPL_SHIFT_EMPL` FOREIGN KEY `EMPL_SHIFT_EMPL` (`FK_EMPLOYEE_ID`)
    REFERENCES `PUBLIC`.`EMPLOYEE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `SHIFT_SHIFT_EMPL` FOREIGN KEY `SHIFT_SHIFT_EMPL` (`FK_SHIFT_ID`)
    REFERENCES `PUBLIC`.`SHIFT` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`DESIGNER`;
CREATE TABLE `PUBLIC`.`DESIGNER` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_DESIGNER_10112` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10111_10113` (`NAME`)
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`DAILY_SHEET`;
CREATE TABLE `PUBLIC`.`DAILY_SHEET` (
  `ID` BIGINT(64) NOT NULL,
  `DATE` DATE NULL,
  `FK_EMPLOYEE_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_DAILY_SHEET_10116` (`ID`),
  INDEX `SYS_IDX_10117` (`FK_EMPLOYEE_ID`),
  CONSTRAINT `DS_EMPL` FOREIGN KEY `DS_EMPL` (`FK_EMPLOYEE_ID`)
    REFERENCES `PUBLIC`.`EMPLOYEE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`DAILY_SHEET_SHIFT`;
CREATE TABLE `PUBLIC`.`DAILY_SHEET_SHIFT` (
  `ID` BIGINT(64) NOT NULL,
  `FK_SHIFT_ID` BIGINT(64) NOT NULL,
  `FK_DAILY_SHEET_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_DS_SHIFT_10122` (`ID`),
  INDEX `SYS_IDX_10123` (`FK_SHIFT_ID`),
  INDEX `SYS_IDX_10125` (`FK_DAILY_SHEET_ID`),
  CONSTRAINT `DS_DS_SHIFT` FOREIGN KEY `DS_DS_SHIFT` (`FK_DAILY_SHEET_ID`)
    REFERENCES `PUBLIC`.`DAILY_SHEET` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `SHIFT_DS_SHIFT` FOREIGN KEY `SHIFT_DS_SHIFT` (`FK_SHIFT_ID`)
    REFERENCES `PUBLIC`.`SHIFT` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`FURNITURE_CODE`;
CREATE TABLE `PUBLIC`.`FURNITURE_CODE` (
  `ID` BIGINT(64) NOT NULL,
  `PRICED_TYPE` VARCHAR(255) NOT NULL DEFAULT 'FurnitureCode',
  `CODE` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `MANUFACTURER_ID` BIGINT(64) NOT NULL,
  `GROUP_IDENTIFIER` VARCHAR(255) NULL,
  `SURFACE` VARCHAR(255) NULL,
  `ROTATABLE` BOOLEAN NULL,
  `SERVICE_TYPE` VARCHAR(255) NULL,
  `OFFSET_LENGTH` DOUBLE NULL,
  `OFFSET_WIDTH` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_FURNITURE_CODE_10143` (`ID`),
  UNIQUE INDEX `SYS_IDX_FURNITURE_CODE_UNIQ_101` (`CODE`, `NAME`, `MANUFACTURER_ID`, `SURFACE`, `PRICED_TYPE`), -- `OFFSET_LENGTH`, `OFFSET_WIDTH`),
  INDEX `SYS_IDX_10144` (`MANUFACTURER_ID`),
  CONSTRAINT `MANUFACT_FURNITURE_CODE` FOREIGN KEY `MANUFACT_FURNITURE_CODE` (`MANUFACTURER_ID`)
    REFERENCES `PUBLIC`.`MANUFACTURER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`FURNITURE_TYPE`;
CREATE TABLE `PUBLIC`.`FURNITURE_TYPE` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `UNIT` VARCHAR(255) NOT NULL,
  `MAT_TYPE` VARCHAR(255) NOT NULL DEFAULT 'furniture',
  `DISCRIMINATOR` VARCHAR(255) NOT NULL DEFAULT 'FurnitureType',
  `TYPE` VARCHAR(255) NULL,
  `HEIGHT` BIGINT(64) NULL,
  `THICKNESS` BIGINT(64) NULL,
  `DEFAULT_LENGTH` BIGINT(64) NULL,
  `DEFAULT_WIDTH` BIGINT(64) NULL,
  `SIMPLE_ID_1` BIGINT(64) NULL,
  `SIMPLE_ID_2` BIGINT(64) NULL,
  `OFFSET_LENGTH` DOUBLE NULL,
  `OFFSET_WIDTH` DOUBLE NULL,
  `CUTTER_ID` BIGINT(64) NULL,
  `DEFAULT_SIZE` DOUBLE NOT NULL DEFAULT 1.0E0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_FURNITURE_TYPE_10154` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10153_10155` (`NAME`),
  INDEX `SYS_IDX_10156` (`SIMPLE_ID_1`),
  INDEX `SYS_IDX_10158` (`SIMPLE_ID_2`),
  INDEX `SYS_IDX_10160` (`CUTTER_ID`),
  CONSTRAINT `FURNITURE_TYPE_CUTTER` FOREIGN KEY `FURNITURE_TYPE_CUTTER` (`CUTTER_ID`)
    REFERENCES `PUBLIC`.`CUTTER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BOARD_SIMPLE_TYPE_1` FOREIGN KEY `BOARD_SIMPLE_TYPE_1` (`SIMPLE_ID_1`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BOARD_SIMPLE_TYPE_2` FOREIGN KEY `BOARD_SIMPLE_TYPE_2` (`SIMPLE_ID_2`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`PROVIDER`;
CREATE TABLE `PUBLIC`.`PROVIDER` (
  `ID` BIGINT(64) NOT NULL,
  `SHORT_NAME` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(255) NULL,
  `PHONE_NUMBER` VARCHAR(255) NULL,
  `FAX_NUMBER` VARCHAR(255) NULL,
  `EMAIL_ADDRESS` VARCHAR(255) NULL,
  `OFFICIAL_SITE` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_PROVIDER_10167` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10165_10168` (`SHORT_NAME`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10166_10169` (`NAME`)
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`FURNITURE`;
CREATE TABLE `PUBLIC`.`FURNITURE` (
  `ID` BIGINT(64) NOT NULL,
  `AMOUNT` BIGINT(64) NOT NULL,
  `ORDER_ID` BIGINT(64) NULL,
  `CREATEDBY_ORDER_ID` BIGINT(64) NULL,
  `PROVIDER_ID` BIGINT(64) NULL,
  `FURNITURE_TYPE_ID` BIGINT(64) NOT NULL,
  `FURNITURE_CODE_ID` BIGINT(64) NOT NULL,
  `STATUS` VARCHAR(255) NOT NULL DEFAULT 'order',
  `DELIVERY_ID` BIGINT(64) NULL,
  `PRICE` DOUBLE NOT NULL DEFAULT 0.0E0,
  `ORDERED` BOOLEAN NULL,
  `SIZE` DOUBLE NULL,
  `LENGTH` DOUBLE NULL,
  `WIDTH` BIGINT(64) NULL,
  `DISCRIMINATOR` VARCHAR(255) NOT NULL DEFAULT 'Furniture',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_FURNITURE_10177` (`ID`),
  INDEX `SYS_IDX_10178` (`ORDER_ID`),
  INDEX `SYS_IDX_10180` (`CREATEDBY_ORDER_ID`),
  INDEX `SYS_IDX_10182` (`PROVIDER_ID`),
  INDEX `SYS_IDX_10184` (`FURNITURE_TYPE_ID`),
  INDEX `SYS_IDX_10186` (`FURNITURE_CODE_ID`),
  INDEX `SYS_IDX_10328` (`DELIVERY_ID`),
  CONSTRAINT `FURNITURE_DELIVERY` FOREIGN KEY `FURNITURE_DELIVERY` (`DELIVERY_ID`)
    REFERENCES `PUBLIC`.`DELIVERY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FURNITURE_FURNITURE_CODE` FOREIGN KEY `FURNITURE_FURNITURE_CODE` (`FURNITURE_CODE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_CODE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FURNITURE_FURNITURE_TYPE` FOREIGN KEY `FURNITURE_FURNITURE_TYPE` (`FURNITURE_TYPE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FURNITURE_ORDER` FOREIGN KEY `FURNITURE_ORDER` (`ORDER_ID`)
    REFERENCES `PUBLIC`.`FURN_ORDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FURNITURE_CREATED_ORDER` FOREIGN KEY `FURNITURE_CREATED_ORDER` (`CREATEDBY_ORDER_ID`)
    REFERENCES `PUBLIC`.`FURN_ORDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FURNITURE_PROVIDER` FOREIGN KEY `FURNITURE_PROVIDER` (`PROVIDER_ID`)
    REFERENCES `PUBLIC`.`PROVIDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`DELIVERY`;
CREATE TABLE `PUBLIC`.`DELIVERY` (
  `ID` BIGINT(64) NOT NULL,
  `DELIVERY_DATE` DATE NOT NULL,
  `PROVIDER_ID` BIGINT(64) NOT NULL,
  `MAT_TYPE` VARCHAR(255) NOT NULL DEFAULT 'border',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_PK_10189_10193` (`ID`),
  INDEX `SYS_IDX_10194` (`PROVIDER_ID`),
  CONSTRAINT `PROVIDER_DELIVERY` FOREIGN KEY `PROVIDER_DELIVERY` (`PROVIDER_ID`)
    REFERENCES `PUBLIC`.`PROVIDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`STORAGE_ELEMENT_LINK`;
CREATE TABLE `PUBLIC`.`STORAGE_ELEMENT_LINK` (
  `ID` BIGINT(64) NOT NULL,
  `AMOUNT` BIGINT(64) NOT NULL,
  `ORDER_ID` BIGINT(64) NOT NULL,
  `FURNITURE_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_BOARD_LINK_10200` (`ID`),
  INDEX `SYS_IDX_10201` (`ORDER_ID`),
  INDEX `SYS_IDX_10203` (`FURNITURE_ID`),
  CONSTRAINT `STORAGE_FURN_CONSTR` FOREIGN KEY `STORAGE_FURN_CONSTR` (`FURNITURE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BOARD_LINK_ORDER` FOREIGN KEY `BOARD_LINK_ORDER` (`ORDER_ID`)
    REFERENCES `PUBLIC`.`FURN_ORDER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`ORDER_GROUP`;
CREATE TABLE `PUBLIC`.`ORDER_GROUP` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `DAILYSHEET_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_ORDER_GROUP_10208` (`ID`),
  INDEX `SYS_IDX_10209` (`DAILYSHEET_ID`),
  CONSTRAINT `ORDER_GROUP_DAILYSHEED` FOREIGN KEY `ORDER_GROUP_DAILYSHEED` (`DAILYSHEET_ID`)
    REFERENCES `PUBLIC`.`DAILY_SHEET` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`ORDER_GROUP_LINK`;
CREATE TABLE `PUBLIC`.`ORDER_GROUP_LINK` (
  `ID` BIGINT(64) NOT NULL,
  `ORDER_ID` BIGINT(64) NOT NULL,
  `GROUP_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_ORDER_GROUP_LINK_102` (`ID`),
  INDEX `SYS_IDX_10215` (`ORDER_ID`),
  INDEX `SYS_IDX_10217` (`GROUP_ID`),
  CONSTRAINT `ORDER_ORDER_GROUP_LINK` FOREIGN KEY `ORDER_ORDER_GROUP_LINK` (`ORDER_ID`)
    REFERENCES `PUBLIC`.`FURN_ORDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `GROUP_ORDER_GROUP_LINK` FOREIGN KEY `GROUP_ORDER_GROUP_LINK` (`GROUP_ID`)
    REFERENCES `PUBLIC`.`ORDER_GROUP` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`CURRENCY`;
CREATE TABLE `PUBLIC`.`CURRENCY` (
  `ID` BIGINT(64) NOT NULL,
  `TYPE` VARCHAR(255) NOT NULL,
  `PRICE` DOUBLE NOT NULL,
  `DAILYSHEET_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_CURRENCY_10224` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10223_10225` (`TYPE`, `DAILYSHEET_ID`),
  INDEX `SYS_IDX_10226` (`DAILYSHEET_ID`),
  CONSTRAINT `CURRENCY_DAILYSHEET` FOREIGN KEY `CURRENCY_DAILYSHEET` (`DAILYSHEET_ID`)
    REFERENCES `PUBLIC`.`DAILY_SHEET` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`FURNITURE_TYPE_LINK`;
CREATE TABLE `PUBLIC`.`FURNITURE_TYPE_LINK` (
  `ID` BIGINT(64) NOT NULL,
  `KEYWORD` VARCHAR(255) NOT NULL,
  `PARENT_ID` BIGINT(64) NOT NULL,
  `CHILD_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_FURNITURE_TYPE_LINK_` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10232_10234` (`KEYWORD`, `PARENT_ID`, `CHILD_ID`),
  INDEX `SYS_IDX_10235` (`PARENT_ID`),
  INDEX `SYS_IDX_10237` (`CHILD_ID`),
  CONSTRAINT `PLINK_FURNITURE_TYPE` FOREIGN KEY `PLINK_FURNITURE_TYPE` (`PARENT_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `CLINK_FURNITURE_TYPE` FOREIGN KEY `CLINK_FURNITURE_TYPE` (`CHILD_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`FURNITURE_CODE_LINK`;
CREATE TABLE `PUBLIC`.`FURNITURE_CODE_LINK` (
  `ID` BIGINT(64) NOT NULL,
  `KEYWORD` VARCHAR(255) NOT NULL,
  `PARENT_ID` BIGINT(64) NOT NULL,
  `CHILD_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_FURNITURE_CODE_LINK_` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10243_10245` (`KEYWORD`, `PARENT_ID`, `CHILD_ID`),
  INDEX `SYS_IDX_10246` (`PARENT_ID`),
  INDEX `SYS_IDX_10248` (`CHILD_ID`),
  CONSTRAINT `PLINK_FURNITURE_CODE` FOREIGN KEY `PLINK_FURNITURE_CODE` (`PARENT_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_CODE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `CLINK_FURNITURE_CODE` FOREIGN KEY `CLINK_FURNITURE_CODE` (`CHILD_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_CODE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`FURN_LINK_FURN_LINK`;
CREATE TABLE `PUBLIC`.`FURN_LINK_FURN_LINK` (
  `ID` BIGINT(64) NOT NULL,
  `KEYWORD` VARCHAR(255) NOT NULL,
  `PARENT_ID` BIGINT(64) NOT NULL,
  `CHILD_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_FURN_LINK_FURN_LINK_` (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_CT_10254_10256` (`KEYWORD`, `PARENT_ID`, `CHILD_ID`),
  INDEX `SYS_IDX_10257` (`PARENT_ID`),
  INDEX `SYS_IDX_10259` (`CHILD_ID`),
  CONSTRAINT `CFLFL_FURNITURE` FOREIGN KEY `CFLFL_FURNITURE` (`CHILD_ID`)
    REFERENCES `PUBLIC`.`FURNITURE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `PFLFL_ORDER_DETAIL` FOREIGN KEY `PFLFL_ORDER_DETAIL` (`PARENT_ID`)
    REFERENCES `PUBLIC`.`ORDER_DETAIL` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`COMMON_DATA`;
CREATE TABLE `PUBLIC`.`COMMON_DATA` (
  `ID` BIGINT(64) NOT NULL,
  `DISCRIMINATOR` VARCHAR(255) NOT NULL,
  `CTYPE` VARCHAR(255) NOT NULL,
  `SERVICE` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `AMOUNT` DOUBLE NOT NULL,
  `PRICE` DOUBLE NOT NULL,
  `DIALER_PRICE` DOUBLE NOT NULL,
  `LAST` BOOLEAN NOT NULL,
  `ORDER_ID` BIGINT(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_COMMON_DATA_10271` (`ID`),
  INDEX `SYS_IDX_10272` (`ORDER_ID`),
  CONSTRAINT `COMMON_DATA_ORDER` FOREIGN KEY `COMMON_DATA_ORDER` (`ORDER_ID`)
    REFERENCES `PUBLIC`.`FURN_ORDER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`DILER_ORDER`;
CREATE TABLE `PUBLIC`.`DILER_ORDER` (
  `ID` BIGINT(64) NOT NULL,
  `COST` DOUBLE NULL,
  `ORDER_NUMBER` BIGINT(64) NULL,
  `READY_DATE` DATE NULL,
  `NAME` VARCHAR(255) NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  `FK_CREATED_DAILY_SHEET_ID` BIGINT(64) NULL,
  `FK_WORKED_DAILY_SHEET_ID` BIGINT(64) NULL,
  `FK_CUSTOMER_ID` BIGINT(64) NULL,
  `FK_DESIGNER_ID` BIGINT(64) NULL,
  `STATUS` VARCHAR(255) NULL DEFAULT 'design',
  `ORDER_ID` BIGINT(64) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_PK_10275_10276` (`ID`),
  INDEX `SYS_IDX_10277` (`FK_CUSTOMER_ID`),
  CONSTRAINT `DILER_ORDER_CUSTOMER_CONSTR` FOREIGN KEY `DILER_ORDER_CUSTOMER_CONSTR` (`FK_CUSTOMER_ID`)
    REFERENCES `PUBLIC`.`CUSTOMER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`DILER_ORDER_DETAIL`;
CREATE TABLE `PUBLIC`.`DILER_ORDER_DETAIL` (
  `ID` BIGINT(64) NOT NULL,
  `NUMBER` BIGINT(64) NULL,
  `NAME` VARCHAR(255) NULL,
  `LENGTH` BIGINT(64) NULL,
  `WIDTH` BIGINT(64) NULL,
  `AMOUNT` BIGINT(64) NULL,
  `ROTATABLE` BOOLEAN NULL,
  `GLUEING` VARCHAR(255) NULL,
  `MILLING` VARCHAR(255) NULL,
  `GROOVE` VARCHAR(255) NULL,
  `ANGLE45` VARCHAR(255) NULL,
  `DRILLING` VARCHAR(255) NULL,
  `CUTOFF` VARCHAR(255) NULL,
  `FURNITURE_TYPE_ID` BIGINT(64) NULL,
  `FURNITURE_CODE_ID` BIGINT(64) NULL,
  `COMLEX_BOARD_DEF_ID` BIGINT(64) NULL,
  `SECOND_BOARD_ID` BIGINT(64) NULL,
  `ORDER_ITEM_ID` BIGINT(64) NULL,
  `FPRIMARY` BOOLEAN NULL,
  `DISCRIMINATOR` VARCHAR(255) NULL DEFAULT 'OrderFurniture',
  `TYPE` VARCHAR(255) NULL,
  `PRICE` DOUBLE NULL,
  `FURNITURE_ID` BIGINT(64) NULL,
  `SIZE` DOUBLE NULL,
  `SIDE` VARCHAR(255) NULL,
  `DILER_ORDER_ITEM_ID` BIGINT(64) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_PK_10280_10281` (`ID`),
  INDEX `SYS_IDX_10282` (`FURNITURE_TYPE_ID`),
  INDEX `SYS_IDX_10284` (`COMLEX_BOARD_DEF_ID`),
  INDEX `SYS_IDX_10286` (`FURNITURE_CODE_ID`),
  INDEX `SYS_IDX_10330` (`DILER_ORDER_ITEM_ID`),
  CONSTRAINT `DILER_ORDER_DETAIL_CONSTR` FOREIGN KEY `DILER_ORDER_DETAIL_CONSTR` (`DILER_ORDER_ITEM_ID`)
    REFERENCES `PUBLIC`.`DILER_ORDER_ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DILER_ORDER_DETAIL_FURNITURE_CODE_CONSTR` FOREIGN KEY `DILER_ORDER_DETAIL_FURNITURE_CODE_CONSTR` (`FURNITURE_CODE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_CODE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DILER_ORDER_DETAIL_FURNITURE_TYPE_CONSTR` FOREIGN KEY `DILER_ORDER_DETAIL_FURNITURE_TYPE_CONSTR` (`FURNITURE_TYPE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DILER_ORDER_DETAIL_COMLEX_BOARD_DEF_CONSTR` FOREIGN KEY `DILER_ORDER_DETAIL_COMLEX_BOARD_DEF_CONSTR` (`COMLEX_BOARD_DEF_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`DILER_ORDER_ITEM`;
CREATE TABLE `PUBLIC`.`DILER_ORDER_ITEM` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NULL,
  `ORDER_ID` BIGINT(64) NULL,
  `TYPE` VARCHAR(255) NULL DEFAULT 'first',
  `NUMBER` BIGINT(64) NULL DEFAULT 1,
  `AMOUNT` BIGINT(64) NULL DEFAULT 1,
  `LENGTH` DOUBLE NULL,
  `WIDTH` DOUBLE NULL,
  `DISCRIMINATOR` VARCHAR(255) NULL DEFAULT 'OrderItem',
  `DILER_ORDER_ID` BIGINT(64) NULL,
  `ORDER_ITEM_ID` BIGINT(64) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_SYS_PK_10289_10290` (`ID`),
  INDEX `SYS_IDX_10291` (`DILER_ORDER_ID`),
  CONSTRAINT `DILER_ORDER_ITEM_CONSTR` FOREIGN KEY `DILER_ORDER_ITEM_CONSTR` (`DILER_ORDER_ID`)
    REFERENCES `PUBLIC`.`DILER_ORDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS `PUBLIC`.`CATEGORY`;
CREATE TABLE `PUBLIC`.`CATEGORY` (
  `ID` BIGINT(64) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` LONGTEXT NULL,
  `FILE_UUID` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_CATEGORY_10295` (`ID`)
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;


DROP TABLE IF EXISTS `PUBLIC`.`STRIPS`;
CREATE TABLE `PUBLIC`.`STRIPS` (
  `ID` BIGINT(64) NOT NULL,
  `FURNITURE_CODE_ID` BIGINT(64) NOT NULL,
  `FURNITURE_TYPE_ID` BIGINT(64) NOT NULL,
  `SAW_WIDTH` BIGINT(64) NOT NULL,
  `ROTATION` BOOLEAN NOT NULL,
  `PAIDVALUE` DOUBLE NOT NULL DEFAULT 0.0E0,
  `STRIPS` LONGTEXT NOT NULL,
  `ORDER_ID` BIGINT(64) NULL DEFAULT NULL,
  `DISCRIMINATOR` VARCHAR(255) NOT NULL DEFAULT 'StripsEntity',
  `ORDER_GROUP_ID` BIGINT(64) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SYS_IDX_PK_STRIPS_10135` (`ID`),
  INDEX `SYS_IDX_10136` (`ORDER_ID`),
  INDEX `SYS_IDX_10322` (`FURNITURE_TYPE_ID`),
  INDEX `SYS_IDX_10324` (`FURNITURE_CODE_ID`),
  INDEX `SYS_IDX_10326` (`ORDER_GROUP_ID`),
  CONSTRAINT `STRIPS_FURNITURE_CODE` FOREIGN KEY `STRIPS_FURNITURE_CODE` (`FURNITURE_CODE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_CODE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `STRIPS_FURNITURE_TYPE` FOREIGN KEY `STRIPS_FURNITURE_TYPE` (`FURNITURE_TYPE_ID`)
    REFERENCES `PUBLIC`.`FURNITURE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `STRIPS_ORDER` FOREIGN KEY `STRIPS_ORDER` (`ORDER_ID`)
    REFERENCES `PUBLIC`.`FURN_ORDER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `STRIPS_ORDER_GROUP` FOREIGN KEY `STRIPS_ORDER_GROUP` (`ORDER_GROUP_ID`)
    REFERENCES `PUBLIC`.`ORDER_GROUP` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `public`.`hibernate_sequences` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `sequence_next_hi_value` INT(11) NOT NULL ,
  `sequence_name` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `sequence_name_UNIQUE` (`sequence_name` ASC) )
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_general_ci;
SET FOREIGN_KEY_CHECKS = 1;

-- ----------------------------------------------------------------------
-- EOF

