create table A1 (ID bigint generated by default as identity);
create table A2 (ID bigint generated by default as identity);
create table B2 (ID bigint generated by default as identity, A_ID bigint null);
