INSERT INTO MANUFACTURER (ID, SHORT_NAME, NAME, ADDRESS, PHONE_NUMBER, FAX_NUMBER, EMAIL_ADDRESS, OFFICIAL_SITE)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'KRONOPOL', 'KRONOPOL Swiss Krono Group', 'ul. Serbska, 56 68-200 Zary, POLSKA/POLAND',
'+48 68 36 31 362', '+48 68 36 31 294', 'info@kronopol.com.pl', 'www.kronopol.com.pl');