INSERT INTO BORDER_DEF (ID, NAME, HEIGHT, THICKNESS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ПВХ 1x22', 22, 1);
INSERT INTO BORDER_DEF (ID, NAME, HEIGHT, THICKNESS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ПВХ 1x33', 33, 1);
INSERT INTO BORDER_DEF (ID, NAME, HEIGHT, THICKNESS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ПВХ 1x42', 42, 1);
INSERT INTO BORDER_DEF (ID, NAME, HEIGHT, THICKNESS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ПВХ 2x22', 22, 2);
INSERT INTO BORDER_DEF (ID, NAME, HEIGHT, THICKNESS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ПВХ 2x33', 33, 2);
INSERT INTO BORDER_DEF (ID, NAME, HEIGHT, THICKNESS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ПВХ 2x42', 42, 2);
COMMIT;