INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 7780, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'Acacia', 'Акация');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2460, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'MAT', 'Maple white', 'Клен белый');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2453, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'Toscany Walnut', 'Орех Toskania');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2446, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SM', 'Macassar', 'Macassar');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2427, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'Wenge light', 'Wenge светлое');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2419, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'Antique oak', 'Дуб античный');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2387, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'Antique pine', 'Сосна античная');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2298, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'MAT', 'Seagrass', 'Морская трава');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2297, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'Zebrano dark', 'Темное Zebrano');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2296, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'MAT', 'African Zebrano', 'Африканское Zebrano');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 881, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'METALIC', 'МЕТАЛИК');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2227, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'WENGE', 'WENGE');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2226, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'WENGE MAGIC', 'WENGE MAGIA');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2381, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'PINE', 'Кедр');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2380, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'CHOCOLATE PINE', 'ШОКОЛАДНЫЙ КЕДР');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9261, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'CHESTNUT', 'КАШТАН');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9341, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'GREEN BIRCH', 'БЕРЕЗА ЗЕЛЕНАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9324, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'MALMOE PINE', 'СОСНА МАЛЬМОЭ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9320, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'HONEY PINE', 'СОСНА МЕДОВАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9313, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'CORDOBA PEAR', 'ГРУША КОРДОБА');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 1625, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'DARK WILD PEAR', 'ГРУША СТЕПНАЯ ТЕМНАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 1354, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'ROMA PEAR', 'ГРУША РОМА');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9300, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'WILD PEAR', 'ГРУША СТЕПНАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 664, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'WILD PEAR', 'ГРУША ДИКАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 401 , 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'LIGHT PEAR', 'ГРУША СВЕТЛАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 228, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'PASTEL PEAR', 'ГРУША ПАСТЕЛЬ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9476, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'GOLDOS APPLE', 'ЯБЛОНЯ ГОЛЬДОС');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9475, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'LOCARNO LIGHT APPLE', 'ЯБЛОНЯ ЛОКАРНО СВЕТЛАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 1972, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'LOCARNO APPLE', 'ЯБЛОНЯ ЛОКАРНО');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9164, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'CARAVAGGIO WALNUT', 'ОРЕХ CARAVAGGIO');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9163, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'ECCO WALNUT', 'ОРЕХ ECCO');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9450, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'DARK WALNUT', 'ОРЕХ ТЁМНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9451, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'BOLOGNA WALNUT', 'ОРЕХ БОЛОНИЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 1248, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'FENICE WALNUT', 'ОРЕХ ФЭНИЧЕ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 722, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'WALNUT', 'ОРЕХ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9310, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'ALDER', 'ОЛЬХА');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9311, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'MOUNTAIN ALDER', 'ОЛЬХА ГОРНАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9119, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'WINDSOR OAK DARK', 'ДУБ ВИНДСОР ТЁМНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9118, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'WINDSOR OAK', 'ДУБ ВИНДСОР');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9116, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'WASHED OAK', 'ДУБ МОЛОЧНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 740, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'LIGHT OAK', 'ДУБ СВЕТЛЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9103, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'LIGHT OAK', 'ДУБ СВЕТЛЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9102, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'RUSTICAL OAK', 'ДУБ РУСТИКАЛЬНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 708, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'RUSTICAL OAK', 'ДУБ РУСТИКАЛЬНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 071, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'SEDAN OAK', 'ДУБ СЕДАН');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 775, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'REDWOOD', 'КРАСНОЕ ДЕРЕВО');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 466, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'TOGO MAHOGANY', 'КРАСНОЕ ДЕРЕВО ТОГО');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9352, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'VANCOUVER MAPLE', 'КЛЕН ВАНКУВЕР');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 440, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'VANCOUVER LIGHT MAPLE', 'КЛЕН ВАНКУВЕР СВЕТЛЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 375, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'NATURAL MAPLE', 'КЛЕН НАТУРАЛЬНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2361, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'SWEET CHERRY', 'ЧЕРЕШНЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2360, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'BS', 'ANTIQUE CHERRY', 'ВИШНЯ АНТИЧНАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 344, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'CHERRY', 'ВИШНЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 088, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'OXFORD CHERRY', 'ВИШНЯ ОКСФОРД');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 2201, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'ROTKERN BEECH', 'БУК');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9201, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'MANGFALL LIGHT BEECH', 'БУК МАНГФАЛЬ СВЕТЛЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9200, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PR', 'BAVARIA BEECH', 'БУК БАВАРИЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 1923, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'SAMERBERG BEECH', 'БУК САМЕРБЕРГ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 381, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'BEECH', 'БУК');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 495, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'ELYSEE', 'ЭЛИЗА');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9612, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'BLUE TERRA', 'ТЕРРА ГОЛУБАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9611, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'SALMON TERRA', 'ТЕРРА ЛОСОСЕВАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 9610, 'D', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'YELLOW TERRA', 'ТЕРРА ЖЕЛТАЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 190, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'BLACK', 'ЧЕРНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 155, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'GREEN', 'ЗЕЛЕНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 7100, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'LIGHT GREEN', 'ЗЕЛЕНЫЙ СВЕТЛЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 1310, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'GREEN PASTEL', 'ЗЕЛЕНЫЙ ПАСТЕЛЬНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 126, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'CELADON', 'САЛАТНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 125, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'BLUE', 'ГОЛУБОЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 121, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'LIGHT BLUE', 'ГОЛУБОЙ СВЕТЛЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 119, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'LIGHT BEIGE', 'БЕЖЕВЫЙ СВЕТЛЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 112, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'GREY', 'ПЕПЕЛЬНЫЙ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 1301, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'PE', 'VANILLA', 'ВАНИЛИЯ');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 110, 'K', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SM', 'WHITE 110', 'БЕЛЫЙ 110');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 101, 'K', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SE', 'FRONT WHITE', 'БЕЛЫЙ 101');
INSERT INTO TEXTURE (ID, CODE, GROUP_IDENTIFIER, FK_MANUFACTURER_ID, ROTATABLE, SURFACE, NAME_ENG, NAME_RUS)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 511, 'U', select ID from MANUFACTURER where SHORT_NAME = 'KRONOPOL', false, 'SM', 'WHITE 511', 'БЕЛЫЙ 511');