ALTER TABLE ORDER_DETAIL ALTER GLUEING VARCHAR(1024);
ALTER TABLE ORDER_DETAIL ALTER MILLING VARCHAR(1024);
ALTER TABLE ORDER_DETAIL ALTER GROOVE VARCHAR(1024);
ALTER TABLE ORDER_DETAIL ALTER ANGLE45 VARCHAR(1024);
ALTER TABLE ORDER_DETAIL ALTER DRILLING VARCHAR(1024);
ALTER TABLE ORDER_DETAIL ALTER CUTOFF VARCHAR(1024);
