/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMaterialTypePanel.java
 *
 * Created on 26.11.2009, 23:33:33
 */

package by.dak.swing.tree;

import by.dak.swing.table.ListNaviTable;
import by.dak.swing.table.ListUpdater;
import by.dak.swing.table.ListUpdaterProvider;

import javax.swing.*;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreePath;
import java.awt.*;

/**
 * @author admin
 */
public class MainMaterialTypePanel extends javax.swing.JPanel
{

    /**
     * Creates new form MainMaterialTypePanel
     */
    public MainMaterialTypePanel()
    {
        initComponents();
        initEnvironment();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSplitPane1 = new javax.swing.JSplitPane();
        backPanel = new javax.swing.JPanel();
        listNaviTable = new by.dak.swing.table.ListNaviTable();
        jLabel1 = new javax.swing.JLabel();
        treePanel = new by.dak.swing.tree.ATreePanel();

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        backPanel.setName("backPanel"); // NOI18N
        backPanel.setLayout(new java.awt.BorderLayout());

        listNaviTable.setName("listNaviTable"); // NOI18N
        backPanel.add(listNaviTable, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Нет данных");
        jLabel1.setEnabled(false);
        jLabel1.setName("jLabel1"); // NOI18N
        backPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(backPanel);

        treePanel.setName("treePanel"); // NOI18N
        jSplitPane1.setLeftComponent(treePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private by.dak.swing.table.ListNaviTable listNaviTable;
    private by.dak.swing.tree.ATreePanel treePanel;
    // End of variables declaration//GEN-END:variables

    public ListNaviTable getListNaviTable()
    {
        return listNaviTable;
    }

    public ATreePanel getTreePanel()
    {
        return treePanel;
    }

    private void initEnvironment()
    {
        getTreePanel().getTree().addTreeSelectionListener(new TreeSelectionListener()
        {
            @Override
            public void valueChanged(TreeSelectionEvent e)
            {
                setShowData(false);
                TreePath treePath = e.getNewLeadSelectionPath();
                if (treePath != null)
                {
                    Object o = treePath.getLastPathComponent();
                    if (o instanceof ListUpdaterProvider)
                    {
                        ListUpdater listUpdater = ((ListUpdaterProvider) o).getListUpdater();
                        getListNaviTable().setListUpdater(listUpdater);
                        getListNaviTable().init();
                        setShowData(true);
                    }
                }
            }
        });
    }

    private void setShowData(boolean show)
    {
        JComponent remove = show ? jLabel1 : getListNaviTable();
        JComponent add = show ? getListNaviTable() : jLabel1;
        backPanel.remove(remove);
        backPanel.add(add, BorderLayout.CENTER);

//        backPanel.revalidate();
//        backPanel.invalidate();
//        backPanel.validate();
        backPanel.repaint();

        add.revalidate();
        add.invalidate();
        add.validate();
    }


}
