--delete unique constraing from FURN_ORDER.ORDER_NUMBER
CREATE TABLE FURN_ORDER_TEMP (ID BIGINT, ORDER_NUMBER BIGINT);
INSERT INTO FURN_ORDER_TEMP(ID,ORDER_NUMBER) SELECT ID, ORDER_NUMBER FROM  FURN_ORDER;
ALTER TABLE FURN_ORDER DROP COLUMN ORDER_NUMBER;
ALTER TABLE FURN_ORDER ADD ORDER_NUMBER BIGINT;
UPDATE FURN_ORDER FO SET ORDER_NUMBER = (select ORDER_NUMBER from FURN_ORDER_TEMP fot where fot.ID = fo.id);
ALTER TABLE FURN_ORDER ALTER COLUMN ORDER_NUMBER SET NOT NULL;
DROP TABLE FURN_ORDER_TEMP;
