drop table PRICE CASCADE;

create table PRICE (ID bigint generated by default as identity,
FK_BORDER_DEF_ID bigint null,
FK_BOARD_DEF_ID bigint null,
FK_TEXTURE_ID bigint null,
SERVICE varchar(255) null,
PRICE  bigint null,
PRICE_DEALER  bigint null,
PRICE_FAKTOR  float null,
constraint PK_PRICE primary key (ID));

alter table PRICE add constraint BORDER_PRICE foreign key (FK_BORDER_DEF_ID) references BORDER_DEF;
alter table PRICE add constraint BOARD_PRICE foreign key (FK_BOARD_DEF_ID) references FURNITURE_DEF;
alter table PRICE add constraint TEXTURE_PRICE foreign key (FK_TEXTURE_ID) references TEXTURE;
alter table PRICE add constraint PRICE_UNIQUE unique (FK_BOARD_DEF_ID, FK_TEXTURE_ID,FK_BORDER_DEF_ID,SERVICE);

commit;