create table ORDER_GROUP_LINK(ID bigint generated by default as identity,
ORDER_ID bigint not null,
GROUP_ID bigint not null,
constraint PK_ORDER_GROUP_LINK primary key (ID)
);

alter table ORDER_GROUP_LINK add constraint ORDER_ORDER_GROUP_LINK foreign key (ORDER_ID) references FURN_ORDER;
alter table ORDER_GROUP_LINK add constraint GROUP_ORDER_GROUP_LINK foreign key (GROUP_ID) references ORDER_GROUP;
