-- FURNITURE_CODE
create table FURNITURE_CODE (ID bigint generated by default as identity,
PRICED_TYPE VARCHAR(255) DEFAULT 'FurnitureCode' not null,
CODE varchar(255) not null,
NAME varchar(255) not null,
MANUFACTURER_ID bigint not null,
constraint PK_FURNITURE_CODE primary key (ID),
constraint FURNITURE_CODE_UNIQ unique (CODE));

-- FURNITURE_TYPE
create table FURNITURE_TYPE (ID bigint generated by default as identity,
NAME varchar(255) not null,
UNIT VARCHAR(255) DEFAULT null,
MAT_TYPE VARCHAR(255) DEFAULT 'furniture' not null,
constraint PK_FURNITURE_TYPE primary key (ID), unique (NAME));
