create table FURNITURE_LINK (ID bigint generated by default as identity,
AMOUNT bigint not null,
FURNITURE_CODE_ID bigint not null,
FURNITURE_TYPE_ID bigint not null,
FURN_ORDER_ID bigint not null,
FURNITURE_ID bigint null,
constraint PK_FURNITURE_LINK primary key (ID)
);

alter table FURNITURE_LINK add constraint FURNITURE_CODE_FURNITURE_LINK foreign key (FURNITURE_CODE_ID) references FURNITURE_CODE;
alter table FURNITURE_LINK add constraint FURNITURE_TYPE_FURNITURE_LINK foreign key (FURNITURE_TYPE_ID) references FURNITURE_TYPE;
alter table FURNITURE_LINK add constraint FURN_ORDER_FURNITURE_LINK foreign key (FURN_ORDER_ID) references FURN_ORDER;
alter table FURNITURE_LINK add constraint FURNITURE_FURNITURE_LINK foreign key (FURNITURE_ID) references FURNITURE;