create table FURNITURE (ID bigint generated by default as identity,
AMOUNT bigint not null,
ORDER_ID bigint null,
CREATEDBY_ORDER_ID bigint null,
PROVIDER_ID bigint null,
FURNITURE_TYPE_ID bigint not null,
FURNITURE_CODE_ID bigint not null,
STATUS VARCHAR(255) DEFAULT 'order' not null,
constraint PK_FURNITURE primary key (ID)
)

alter table FURNITURE add constraint PROVIDER_FURNITURE foreign key (PROVIDER_ID) references PROVIDER;
alter table FURNITURE add constraint FURNITURE_TYPE_FURNITURE foreign key (FURNITURE_TYPE_ID) references FURNITURE_TYPE;
alter table FURNITURE add constraint FURNITURE_CODE_FURNITURE foreign key (FURNITURE_CODE_ID) references FURNITURE_CODE;
alter table FURNITURE add constraint ORDER_FURNITURE foreign key (ORDER_ID) references FURN_ORDER;
alter table FURNITURE add constraint CREATEDBY_ORDER_FURNITURE foreign key (CREATEDBY_ORDER_ID) references FURN_ORDER;
