package by.dak.cutting.swing.store.tabs;

import by.dak.cutting.swing.BaseTabPanel;
import by.dak.cutting.swing.ItemSelector;
import by.dak.persistence.FacadeContext;
import by.dak.persistence.entities.BoardDef;
import com.jgoodies.validation.ValidationResult;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.Bindings;

import java.util.List;

public class BoardDefCompositeTypeTab extends BaseTabPanel<BoardDef>
{
    ResourceMap rsMap = Application.getInstance().getContext().getResourceMap(
            BoardDefTab.class);


    /**
     * Creates new form BoardDefTab
     */

    public BoardDefCompositeTypeTab(BoardDef boardDef)
    {
        setValue(boardDef);
        initComponents();
        initEnvironment();
    }

    private void initEnvironment()
    {
        initBinding();
    }

    @Override
    public ValidationResult validateGui()
    {
        // validate the name field

        // FIXME add extra logic for composite usertype validation
        return new ValidationResult();
    }

    private void initBinding()
    {
        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, getValue(), BeanProperty
                .create("simpleType1"), itemSelectorFirst.getComboBoxItem(), BeanProperty.create("selectedItem"));
        binding.setSourceUnreadableValue(null);
        getBindingGroup().addBinding(binding);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, getValue(), BeanProperty
                .create("simpleType2"), itemSelectorSecond.getComboBoxItem(), BeanProperty.create("selectedItem"));
        binding.setSourceUnreadableValue(null);
        getBindingGroup().addBinding(binding);

        getBindingGroup().bind();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelFirstType = new javax.swing.JLabel();
        labelSecondType = new javax.swing.JLabel();
        itemSelectorFirst = new ItemSelector();
        itemSelectorSecond = new ItemSelector();

        setName("Form"); // NOI18N

        labelFirstType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(
                by.dak.cutting.CuttingApp.class).getContext().getResourceMap(BoardDefCompositeTypeTab.class);
        labelFirstType.setText(resourceMap.getString("labelFirstType.text")); // NOI18N
        labelFirstType.setName("labelFirstType"); // NOI18N

        labelSecondType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSecondType.setText(resourceMap.getString("labelSecondType.text")); // NOI18N
        labelSecondType.setName("labelSecondType"); // NOI18N

        itemSelectorFirst.setName("itemSelectorFirst"); // NOI18N
        itemSelectorSecond.setName("itemSelectorSecond"); // NOI18N

        List<BoardDef> items = FacadeContext.getBoardDefFacade().findSimpleBoardDefs();
        itemSelectorFirst.setItems(items);
        itemSelectorSecond.setItems(items);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(
                                labelSecondType, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(labelFirstType, javax.swing.GroupLayout.DEFAULT_SIZE, 100,
                                        Short.MAX_VALUE)).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                                itemSelectorFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(itemSelectorSecond, javax.swing.GroupLayout.DEFAULT_SIZE, 100,
                                        Short.MAX_VALUE)).addContainerGap()));

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{labelFirstType,
                labelSecondType});

        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
                                labelFirstType, javax.swing.GroupLayout.PREFERRED_SIZE, 19,
                                javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(itemSelectorFirst,
                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(7, 7, 7).addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
                                itemSelectorSecond, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelSecondType, javax.swing.GroupLayout.PREFERRED_SIZE, 19,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(9, 9, 9).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)));

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{labelFirstType,
                labelSecondType,});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{itemSelectorFirst,
                itemSelectorSecond});

    }// </draw-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelFirstType;
    private javax.swing.JLabel labelSecondType;
    private ItemSelector itemSelectorFirst;
    private ItemSelector itemSelectorSecond;


    @Override
    public void setValue(BoardDef value)
    {
        super.setValue(value);    //To change body of overridden methods use File | Settings | File Templates.
    }
}
