package by.dak.cutting.swing.store.tabs;

import by.dak.cutting.CuttingApp;
import by.dak.cutting.swing.BaseTabPanel;
import by.dak.persistence.FacadeContext;
import by.dak.persistence.entities.Manufacturer;
import by.dak.persistence.entities.TextureEntity;
import by.dak.utils.validator.ValidatorAnnotationProcessor;
import com.jgoodies.validation.ValidationResult;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.beansbinding.*;

import javax.swing.*;
import java.beans.Beans;
import java.util.Collections;
import java.util.List;

/**
 * Tab of the TabCtrl for texture entity
 *
 * @author Rudak Alexei
 */
public class TextureTab extends BaseTabPanel
{
    private ResourceMap resourceMap = Application.getInstance(
            CuttingApp.class).getContext().getResourceMap(TextureTab.class);
    private ActionMap actionMap = org.jdesktop.application.Application.getInstance(by.dak.cutting.CuttingApp.class).getContext().getActionMap(TextureTab.class, this);
    private TextureEntity texture;
    private List<Manufacturer> list;
    private final String regExpNumeric = "\\d*";

    public TextureTab(TextureEntity texture)
    {
        this.texture = texture;
        initComponents();
        initEnvironment();
    }

    private void initEnvironment()
    {
        if (!Beans.isDesignTime())
        {
            selectorManuf.setItems(getList());
            fCode.setMask(regExpNumeric);
            initTextureBinding();
        }

    }


    /**
     * @return the listManufacturerEntities
     */
    public List<Manufacturer> getList()
    {
        if (list == null)
        {
            list = (List<Manufacturer>) (Beans.isDesignTime() ? Collections.emptyList() : FacadeContext
                    .getManufacturerFacade().loadAll());
        }
        return list;
    }

    public ValidationResult validateGui()
    {
        return ValidatorAnnotationProcessor.getProcessor().validate(texture);
    }

    private void initTextureBinding()
    {
        BindingGroup bindingGroup = new BindingGroup();
        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, texture, BeanProperty
                .create("name"), fieldNameRus, BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, texture, BeanProperty
                .create("surface"), surface, BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, texture, BeanProperty
                .create("groupIdentifier"), fieldGroupIdentifier, BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, texture, BeanProperty
                .create("rotatable"), checkBoxRotatable, BeanProperty.create("selected"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, texture, BeanProperty
                .create("code"), fCode, BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, texture, BeanProperty
                .create("manufacturer"), selectorManuf.getComboBoxItem(), BeanProperty.create("selectedItem"));
        //binding.setConverter(converter)
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        bindingGroup.bind();
    }

    @Action
    public void showManufacturersDialog()
    {

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        checkBoxRotatable = new javax.swing.JCheckBox();
        selectorManuf = new by.dak.cutting.swing.ItemSelector();
        labelNameRus = new javax.swing.JLabel();
        labelCode = new javax.swing.JLabel();
        labelGroupIdentifier = new javax.swing.JLabel();
        labelNameEng = new javax.swing.JLabel();
        labelSurface = new javax.swing.JLabel();
        labelRotatable = new javax.swing.JLabel();
        labelManufacturer = new javax.swing.JLabel();
        fieldNameRus = new by.dak.cutting.swing.component.MaskTextField();
        fieldNameEng = new by.dak.cutting.swing.component.MaskTextField();
        surface = new by.dak.cutting.swing.component.MaskTextField();
        fCode = new by.dak.cutting.swing.component.MaskTextField();
        fieldGroupIdentifier = new by.dak.cutting.swing.component.MaskTextField();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(364, 204));

        checkBoxRotatable.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        checkBoxRotatable.setName("checkBoxRotatable"); // NOI18N

        selectorManuf.setName("selectorManuf"); // NOI18N
        selectorManuf.setNewAction(actionMap.get("showManufacturersDialog")); // NOI18N
        selectorManuf.setOpaque(false);

        labelNameRus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNameRus.setText(resourceMap.getString("labelNameRus.text")); // NOI18N
        labelNameRus.setName("labelNameRus"); // NOI18N

        labelCode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCode.setText(resourceMap.getString("labelCode.text")); // NOI18N
        labelCode.setName("labelCode"); // NOI18N

        labelGroupIdentifier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelGroupIdentifier.setText(resourceMap.getString("labelGroupIdentifier.text")); // NOI18N
        labelGroupIdentifier.setName("labelGroupIdentifier"); // NOI18N

        labelNameEng.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNameEng.setText(resourceMap.getString("labelNameEng.text")); // NOI18N
        labelNameEng.setName("labelNameEng"); // NOI18N

        labelSurface.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSurface.setText(resourceMap.getString("labelSurface.text")); // NOI18N
        labelSurface.setName("labelSurface"); // NOI18N

        labelRotatable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRotatable.setText(resourceMap.getString("labelRotatable.text")); // NOI18N
        labelRotatable.setName("labelRotatable"); // NOI18N

        labelManufacturer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelManufacturer.setText(resourceMap.getString("labelManufacturer.text")); // NOI18N
        labelManufacturer.setName("labelManufacturer"); // NOI18N

        fieldNameRus.setText(resourceMap.getString("fieldNameRus.text")); // NOI18N
        fieldNameRus.setName("fieldNameRus"); // NOI18N

        fieldNameEng.setText(resourceMap.getString("fieldNameEng.text")); // NOI18N
        fieldNameEng.setName("fieldNameEng"); // NOI18N

        surface.setText(resourceMap.getString("surface.text")); // NOI18N
        surface.setName("surface"); // NOI18N

        fCode.setText(resourceMap.getString("fCode.text")); // NOI18N
        fCode.setName("fCode"); // NOI18N

        fieldGroupIdentifier.setText(resourceMap.getString("fieldGroupIdentifier.text")); // NOI18N
        fieldGroupIdentifier.setName("fieldGroupIdentifier"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelNameRus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(labelManufacturer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(labelRotatable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(labelGroupIdentifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(labelCode, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(labelSurface, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(labelNameEng, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldGroupIdentifier, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(fCode, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(surface, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(fieldNameEng, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(fieldNameRus, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(checkBoxRotatable, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(selectorManuf, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{labelCode, labelGroupIdentifier, labelManufacturer, labelNameEng, labelNameRus, labelRotatable, labelSurface});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{checkBoxRotatable, selectorManuf});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelNameRus, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                        .addComponent(fieldNameRus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelNameEng, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                        .addComponent(fieldNameEng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelSurface)
                                        .addComponent(surface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCode, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelGroupIdentifier)
                                        .addComponent(fieldGroupIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelRotatable, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                        .addComponent(checkBoxRotatable))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                        .addComponent(selectorManuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{checkBoxRotatable, labelCode, labelGroupIdentifier, labelManufacturer, labelNameEng, labelNameRus, labelRotatable, labelSurface, selectorManuf});

    }// </draw-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxRotatable;
    private by.dak.cutting.swing.component.MaskTextField fCode;
    private by.dak.cutting.swing.component.MaskTextField fieldGroupIdentifier;
    private by.dak.cutting.swing.component.MaskTextField fieldNameEng;
    private by.dak.cutting.swing.component.MaskTextField fieldNameRus;
    private javax.swing.JLabel labelCode;
    private javax.swing.JLabel labelGroupIdentifier;
    private javax.swing.JLabel labelManufacturer;
    private javax.swing.JLabel labelNameEng;
    private javax.swing.JLabel labelNameRus;
    private javax.swing.JLabel labelRotatable;
    private javax.swing.JLabel labelSurface;
    private by.dak.cutting.swing.ItemSelector selectorManuf;
    private by.dak.cutting.swing.component.MaskTextField surface;
    // End of variables declaration//GEN-END:variables

}
