/*
 * IndividualView.java
 *
 * Created on 10. listopad 2006, 21:41
 */

package by.dak.cutting.cut.gui.Individual;

import by.dak.cutting.cut.genetics.SRIndividual;

/**
 * @author Peca
 */
public class IndividualView extends javax.swing.JPanel
{

    SRIndividual individual;

    /**
     * Creates new form IndividualView
     */
    public IndividualView()
    {
        initComponents();
    }

    public void setIndividual(SRIndividual individual)
    {
        this.individual = individual;
        update();
    }

    public void update()
    {
        //CommonGui.showIndividualWorkSpace(0, 0, individual);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <draw-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(0, 300, Short.MAX_VALUE)
        );
    }
    // </draw-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
