ALTER table FURNITURE_TYPE add CUTTER_ID bigint;
alter table FURNITURE_TYPE add constraint FURNITURE_TYPE_CUTTER foreign key (CUTTER_ID) references CUTTER;
update FURNITURE_TYPE set CUTTER_ID = 8 where DISCRIMINATOR = 'BoardDef';
INSERT INTO CUTTER (ID, NAME, SAWCUT_WIDTH, CUT_SIZE_LEFT, CUT_SIZE_RIGHT, CUT_SIZE_BOTTOM, CUT_SIZE_TOP) VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Cutter-5-0-0-0-0', 5, 0, 0, 0, 0);
INSERT INTO CUTTER (ID, NAME, SAWCUT_WIDTH, CUT_SIZE_LEFT, CUT_SIZE_RIGHT, CUT_SIZE_BOTTOM, CUT_SIZE_TOP) VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Cutter-1-0-0-0-0', 1, 0, 0, 0, 0);
