ALTER TABLE BOARD_LINK RENAME TO STORAGE_ELEMENT_LINK;
ALTER TABLE STORAGE_ELEMENT_LINK ALTER COLUMN BOARD_ID RENAME TO FURNITURE_ID;
ALTER TABLE STORAGE_ELEMENT_LINK ADD constraint STORAGE_FURN_CONSTR FOREIGN KEY (FURNITURE_ID) REFERENCES FURNITURE;