--FURN_ORDER
alter TABLE FURN_ORDER ADD DILER_ORDER_ID BIGINT;
alter TABLE FURN_ORDER ADD constraint DILER_ORDER_CONSTR FOREIGN KEY (DILER_ORDER_ID) REFERENCES DILER_ORDER;
--DILER_ORDER_ITEM
alter TABLE DILER_ORDER_ITEM ADD DILER_ORDER_ID BIGINT;
alter TABLE DILER_ORDER_ITEM ADD ORDER_ITEM_ID BIGINT;
alter TABLE DILER_ORDER_ITEM ADD constraint DILER_ORDER_ITEM_CONSTR FOREIGN KEY (DILER_ORDER_ID) REFERENCES DILER_ORDER;
--DILER_ORDER_DETAIL
alter TABLE DILER_ORDER_DETAIL ADD DILER_ORDER_ITEM_ID BIGINT;
alter TABLE DILER_ORDER_DETAIL ADD constraint DILER_ORDER_DETAIL_CONSTR FOREIGN KEY (DILER_ORDER_ITEM_ID) REFERENCES DILER_ORDER_ITEM;
alter TABLE DILER_ORDER_DETAIL ADD constraint DILER_ORDER_DETAIL_FURNITURE_TYPE_CONSTR FOREIGN KEY (FURNITURE_TYPE_ID) REFERENCES FURNITURE_TYPE;
alter TABLE DILER_ORDER_DETAIL ADD constraint DILER_ORDER_DETAIL_COMLEX_BOARD_DEF_CONSTR FOREIGN KEY (COMLEX_BOARD_DEF_ID) REFERENCES FURNITURE_TYPE;
alter TABLE DILER_ORDER_DETAIL ADD constraint DILER_ORDER_DETAIL_FURNITURE_CODE_CONSTR FOREIGN KEY (FURNITURE_CODE_ID) REFERENCES FURNITURE_CODE;
--DILER_ORDER
alter TABLE DILER_ORDER ADD constraint DILER_ORDER_CUSTOMER_CONSTR FOREIGN KEY (FK_CUSTOMER_ID) REFERENCES CUSTOMER;