INSERT INTO PROVIDER (ID, SHORT_NAME, NAME, ADDRESS, PHONE_NUMBER, FAX_NUMBER, EMAIL_ADDRESS, OFFICIAL_SITE)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'PR', 'PROVIDER', 'PR_ADDRESS', 'PR_PHONE', 'PR_FAX',
'PR_EMAIL' , 'PR_SITE');
INSERT INTO PROVIDER (ID, SHORT_NAME, NAME, ADDRESS, PHONE_NUMBER, FAX_NUMBER, EMAIL_ADDRESS, OFFICIAL_SITE)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'PR2', 'PROVIDER2', 'PR_ADDRESS2', 'PR_PHONE2', 'PR_FAX2',
'PR_EMAIL2' , 'PR_SITE2');