INSERT INTO BOARD_DEF (ID, NAME, THICKNESS, TYPE, DEFAULT_LENGTH, DEFAULT_WIDTH)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ДСП 10мм', 10, 'BoardDef', 2800, 2070);

INSERT INTO BOARD_DEF (ID, NAME, THICKNESS, TYPE, DEFAULT_LENGTH, DEFAULT_WIDTH)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ДСП 18мм', 18, 'BoardDef', 2800, 2070);

INSERT INTO BOARD_DEF (ID, NAME, THICKNESS, TYPE, SIMPLE_ID_1, SIMPLE_ID_2, DEFAULT_LENGTH, DEFAULT_WIDTH)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ДСП 28мм', 28, 'BoardDef',
select ID from BOARD_DEF where NAME = 'ДСП 10мм',
select ID from BOARD_DEF where NAME = 'ДСП 18мм', 2800, 2070);

INSERT INTO BOARD_DEF (ID, NAME, THICKNESS, TYPE, SIMPLE_ID_1, SIMPLE_ID_2, DEFAULT_LENGTH, DEFAULT_WIDTH)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ДСП 36мм', 36, 'BoardDef',
select ID from BOARD_DEF where NAME = 'ДСП 18мм',
select ID from BOARD_DEF where NAME = 'ДСП 18мм', 2800, 2070);

INSERT INTO BOARD_DEF (ID, NAME, THICKNESS, TYPE, DEFAULT_LENGTH, DEFAULT_WIDTH)
VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'ДВП 4мм', 4, 'BoardDef', 2800, 2070);