INSERT INTO DEPARTMENT (ID, NAME) VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'director');
INSERT INTO EMPLOYEE (ID, NAME, SURNAME,PASSWORD,USERNAME, FK_DEPARTMENT_ID) VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'director', 'director','director','director', select ID from DEPARTMENT where NAME = 'director');
INSERT INTO CUSTOMER (ID, NAME) VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Дилер1');
INSERT INTO CUTTER (ID, NAME, SAWCUT_WIDTH, CUT_SIZE_LEFT, CUT_SIZE_RIGHT, CUT_SIZE_BOTTOM, CUT_SIZE_TOP) VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Cutter-5-7', 5, 7, 7, 7, 7);
COMMIT;
