--boardlink
select O.ORDER_NUMBER, O.NAME, O.READY_DATE,O.STATUS,BD.NAME, T.NAME_RUS, B.LENGTH,B.WIDTH,B.AMOUNT,B.STATUS,BL.AMOUNT  from BOARD_LINK BL
INNER JOIN BOARD B ON  BL.BOARD_ID = B.ID
INNER JOIN TEXTURE T ON B.TEXTURE_ID = T.ID
INNER JOIN BOARD_DEF BD ON B.BOARD_DEF_ID = BD.ID
INNER JOIN FURN_ORDER O ON BL.ORDER_ID = O.ID
ORDER BY
O.READY_DATE,
O.NAME,
B.STATUS;

--boards
SELECT B.ID, B.LENGTH,B.WIDTH,B.AMOUNT,B.STATUS,T.NAME_RUS,
BD.NAME,O.NAME,SE.ID,FO.ORDER_NUMBER from BOARD B
INNER JOIN TEXTURE T ON B.TEXTURE_ID = T.ID
INNER JOIN BOARD_DEF BD ON B.BOARD_DEF_ID = BD.ID
LEFT JOIN FURN_ORDER O ON B.ORDER_ID = O.ID
INNER JOIN SEGMENT SE ON SE.BOARD_ID = B.ID
INNER JOIN STRIPS ST ON SE.FK_STRIPS_ID = ST.ID
INNER JOIN FURN_ORDER_ITEM FOI ON FOI.ID = ST.FK_ORDER_ITEM_ID
INNER JOIN FURN_ORDER FO ON FO.ID = FOI.FK_FURN_ORDER_ID
WHERE
B.STATUS = 'order'
AND
B.ORDER_ID IS NULL
ORDER BY B.AMOUNT;

update BOARD set AMOUNT=1 where AMOUNT=0 and STATUS='used';

-- orders
SELECT O.ORDER_NUMBER, O.NAME, O.READY_DATE, O.STATUS,B.ID, BD.NAME, T.NAME_RUS, B.LENGTH,B.WIDTH,B.AMOUNT,B.STATUS  FROM FURN_ORDER O
INNER JOIN BOARD B ON B.ORDER_ID = O.ID
INNER JOIN TEXTURE T ON B.TEXTURE_ID = T.ID
INNER JOIN BOARD_DEF BD ON B.BOARD_DEF_ID = BD.ID
WHERE
O.ORDER_NUMBER = 186
ORDER BY
O.READY_DATE,
O.ORDER_NUMBER,
O.STATUS,
BD.NAME,
T.NAME_RUS;

--Поиск ORDER_FURNITURE по ORDER
select f.NUMBER, f.FK_TEXTURE_ID from ORDER_FURNITURE f
inner join FURN_ORDER_ITEM foi on f.FK_FURN_ORDER_ITEM_ID = foi.ID
inner join FURN_ORDER fo on fo.ID = foi.FK_FURN_ORDER_ID
where fo.ORDER_NUMBER = 285






