/*
 * To change this template, choose Tools | Templates
 * and open the template in the draw.
 */

/*
 * DailyStatusPanel.java
 *
 * Created on 07.01.2009, 16:19:21
 */

package by.dak.cutting;

import by.dak.persistence.FacadeContext;
import by.dak.persistence.entities.Dailysheet;
import by.dak.utils.convert.StringValueAnnotationProcessor;

import java.beans.Beans;
import java.text.DateFormat;

/**
 * @author admin
 */
public class DailyStatusPanel extends javax.swing.JPanel
{

    /**
     * Creates new form DailyStatusPanel
     */
    public DailyStatusPanel()
    {
        if (!Beans.isDesignTime())
        {
            initComponents();
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelDate = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        labelManager = new javax.swing.JLabel();
        fieldManager = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(by.dak.cutting.CuttingApp.class).getContext().getResourceMap(DailyStatusPanel.class);
        labelDate.setText(resourceMap.getString("labelDate.text")); // NOI18N
        labelDate.setName("labelDate"); // NOI18N

        fieldDate.setText(resourceMap.getString("fieldDate.text")); // NOI18N
        fieldDate.setName("fieldDate"); // NOI18N
        fieldDate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fieldDateActionPerformed(evt);
            }
        });

        labelManager.setText(resourceMap.getString("labelManager.text")); // NOI18N
        labelManager.setName("labelManager"); // NOI18N

        fieldManager.setText(resourceMap.getString("fieldManager.text")); // NOI18N
        fieldManager.setName("fieldManager"); // NOI18N
        fieldManager.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fieldManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelManager)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldManager, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelManager)
                                .addComponent(labelDate))
        );
    }// </draw-fold>//GEN-END:initComponents

    private void fieldManagerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fieldManagerActionPerformed
    {//GEN-HEADEREND:event_fieldManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManagerActionPerformed

    private void fieldDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fieldDateActionPerformed
    {//GEN-HEADEREND:event_fieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldManager;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelManager;
    // End of variables declaration//GEN-END:variables

    private Dailysheet dailysheet;


    public Dailysheet getDailysheetEntity()
    {
        return dailysheet;
    }

    public void setDailysheetEntity(Dailysheet dailysheet)
    {
        this.dailysheet = dailysheet;
        fieldDate.setEditable(false);
        fieldManager.setEditable(false);
        fieldDate.setText(DateFormat.getDateInstance().format(dailysheet.getDate()));
        fieldManager.setText(StringValueAnnotationProcessor.getProcessor().convert(FacadeContext.getEmployee()));
    }

}
