/*
 * FramePrimitiveCutterTest1.java
 *
 * Created on 1. listopad 2006, 11:24
 */

package by.dak.cutting.cut.gui;

import by.dak.cutting.cut.base.*;

/**
 * @author phorny
 */
public class FramePrimitiveCutterTest1 extends javax.swing.JFrame
{

    private PanelWorkSpace panelWS = null;
    private WorkSpace workSpace;
    private CuttedElement[] cuttedElements;
    private PrimitiveCutter cutter;
    private Element[] elements;
    private int indexToCut = 0;

    /**
     * Creates new form FramePrimitiveCutterTest1
     */
    public FramePrimitiveCutterTest1()
    {
        initComponents();
        try
        {
            cutter = new PrimitiveCutter();
            WorkArea[] sheets = new WorkArea[1];
            sheets[0] = new WorkArea(800, 200);
            workSpace = new WorkSpace(sheets);
            elements = new Element[2];
            /*for(int i=0; i<elements.length; i++){
                elements[i] = new Element(rnd.nextInt(100)+10, rnd.nextInt(100)+10, 0, i);
            }*/
            elements[0] = new Element(50, 50, 0);
            elements[1] = new Element(80, 50, 0);
            //  elements[2] = new Element(50, 50, 0, 1);

            cuttedElements = cutter.cut(elements, workSpace);
            CommonGui.visualizeWorkSpace(workSpace, cuttedElements);
        }
        catch (Exception ex)
        {
            System.out.println("chyba " + ex.getMessage());
            ex.printStackTrace();
            //throw ex;
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <draw-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton1MouseClicked(evt);
            }
        });

        jPanel2.add(jButton1);

        getContentPane().add(jPanel2);

        pack();
    }// </draw-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_jButton1MouseClicked
      /*  cuttedElements.add(cutter.by.dak.cutting.cut(elements[indexToCut], workSpace));
        CuttedElement[] cea = new CuttedElement[cuttedElements.size()];
        cea = cuttedElements.toArray(cea);
        panelWS.setCuttedElements(cea);
        indexToCut++;
        indexToCut = (indexToCut % elements.length);*/
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {


        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FramePrimitiveCutterTest1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
