/*
 * FrameTree.java
 *
 * Created on 28. jen 2006, 10:55
 */

package by.dak.cutting.cut.gui;

import by.dak.cutting.cut.genetics.Individual;
import by.dak.cutting.cut.genetics.Population;
import by.dak.cutting.cut.genetics.SRIndividual;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 * @author Peca
 */
public class FrameTree extends javax.swing.JFrame
{

    Population population;

    /**
     * Creates new form FrameTree
     */
    public FrameTree()
    {
        initComponents();
        //jTree1.


    }

    private void addChildNode(Individual ind, DefaultMutableTreeNode parent)
    {
        if (ind.getParent1() == null) return;
        DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(ind.getParent1());
        DefaultMutableTreeNode p2 = new DefaultMutableTreeNode(ind.getParent2());
        parent.add(p1);
        parent.add(p2);
        addChildNode(ind.getParent1(), p1);
        addChildNode(ind.getParent2(), p2);
    }

    private DefaultMutableTreeNode addChildNode2(SRIndividual ind)
    {
/*        DefaultMutableTreeNode pn = 
        
        if(ind.parent1 == null)return;
        DefaultMutableTreeNode p1 = new DefaultMutableTreeNode(ind.parent1.id);
        DefaultMutableTreeNode p2 = new DefaultMutableTreeNode(ind.parent2.id);
        parent.add(p1);
        parent.add(p2);
        addChildNode(ind.parent1, p1);
        addChildNode(ind.parent2, p2);*/
        return null;
    }

    public void populateTree(SRIndividual ind)
    {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(ind);
        addChildNode(ind, root);

        DefaultTreeModel model = new DefaultTreeModel(root);
        jTree1.setModel(model);
        expandAll(jTree1);
    }

    public void populateTree(Population pop)
    {
        this.population = pop;
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("p");
        for (Individual ind : pop.getIndividuals())
        {
            DefaultMutableTreeNode ch = new DefaultMutableTreeNode(ind);
            root.add(ch);
            addChildNode(ind, ch);
        }

        DefaultTreeModel model = new DefaultTreeModel(root);
        jTree1.setModel(model);
        expandAll(jTree1);
    }

    public void expandAll(javax.swing.JTree tree)
    {
        int row = 0;
        while (row < tree.getRowCount())
        {
            tree.expandRow(row);
            row++;
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <draw-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        buttShowWorkspace1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        buttShowWorkspace1.setText("Show Workspace");
        buttShowWorkspace1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buttShowWorkspace1MouseClicked(evt);
            }
        });

        getContentPane().add(buttShowWorkspace1);

        jScrollPane1.setViewportView(jTree1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </draw-fold>//GEN-END:initComponents

    private void buttShowWorkspace1MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_buttShowWorkspace1MouseClicked

        TreePath[] paths = jTree1.getSelectionPaths();
        int y = 0;
        for (int i = 0; i < paths.length; i++)
        {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) paths[i].getLastPathComponent();
            //DefaultMutableTreeNode node = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
            Individual ind = (Individual) node.getUserObject();

            population.rate(ind);
            /*FrameWorkspace frm = CommonGui.showIndividualWorkSpace(500, y, ind);
            frm.hideControls();
            frm.normalizeSize();
            
            y += frm.getHeight();*/
        }
    }//GEN-LAST:event_buttShowWorkspace1MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttShowWorkspace1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

}
