/*
 * PopulationParamsView.java
 *
 * Created on 26. duben 2008, 18:01
 */

package by.dak.cutting.cut.gui;

import by.dak.cutting.cut.genetics.PopulationParams;
import by.dak.cutting.cut.genetics.ReproductionParams;
import by.dak.cutting.cut.genetics.SelectionParams;

import javax.swing.*;

/**
 * @author Peca
 */
public class PopulationParamsView extends MyFrame
{


    /**
     * Creates new form PopulationParamsView
     */
    public PopulationParamsView()
    {
        initComponents();
    }

    public void setPopulationParams(PopulationParams populationParams)
    {
        PopulationParams pp = populationParams;
        ReproductionParams rp = pp.getReproductionParams();
        SelectionParams sp = pp.getSelectionParams();
        lblPopulationSize.setText("Individuals:\t" + pp.getMaxIndividualsCount());
        lblCrossingProp.setText("Crossing prop.:\t" + rp.getCrossingProbability());
        lblMutationProp.setText("Mutation prop.:\t" + rp.getMutationProbability());
        lblElitism.setText("Elitism ratio:\t" + sp.getElitismRatio());
        lblMaximumAge.setText("Maximum age:\t" + sp.getMaximumAge());
        lblMaximumElite.setText("Maximum elite:\t" + sp.getMaximumEliteIndividuals());
        lblMinimumRatio.setText("Minimum ratio:\t" + sp.getMinimumRatioToSurvive());
        lblMinimumToSurvive.setText("Minimum that survives:\t" + sp.getMinimumThatWillSurvive());
        lblKillTwins.setText("KillTwins:\t" + sp.isKillTwins());
        lblNormalize.setText("Normalize:\t" + sp.isShouldNormalize());
    }

    private void addParam(String caption, int value)
    {
        this.addParam(caption, String.valueOf(value));
    }

    private void addParam(String caption, float value)
    {
        this.addParam(caption, String.valueOf(value));
    }

    private void addParam(String caption, String value)
    {
        JLabel lbl = new JLabel();
        lbl.setText(String.format("%s:\t%s", caption, value));
        this.add(lbl);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblPopulationSize = new javax.swing.JLabel();
        lblCrossingProp = new javax.swing.JLabel();
        lblMutationProp = new javax.swing.JLabel();
        lblElitism = new javax.swing.JLabel();
        lblMaximumAge = new javax.swing.JLabel();
        lblMaximumElite = new javax.swing.JLabel();
        lblMinimumRatio = new javax.swing.JLabel();
        lblMinimumToSurvive = new javax.swing.JLabel();
        lblKillTwins = new javax.swing.JLabel();
        lblNormalize = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lblPopulationSize.setText("jLabel1");
        add(lblPopulationSize);

        lblCrossingProp.setText("jLabel2");
        add(lblCrossingProp);

        lblMutationProp.setText("jLabel3");
        add(lblMutationProp);

        lblElitism.setText("jLabel4");
        add(lblElitism);

        lblMaximumAge.setText("jLabel5");
        add(lblMaximumAge);

        lblMaximumElite.setText("jLabel6");
        add(lblMaximumElite);

        lblMinimumRatio.setText("jLabel7");
        add(lblMinimumRatio);

        lblMinimumToSurvive.setText("jLabel1");
        add(lblMinimumToSurvive);

        lblKillTwins.setText("jLabel2");
        add(lblKillTwins);

        lblNormalize.setText("jLabel1");
        add(lblNormalize);
    }// </draw-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCrossingProp;
    private javax.swing.JLabel lblElitism;
    private javax.swing.JLabel lblKillTwins;
    private javax.swing.JLabel lblMaximumAge;
    private javax.swing.JLabel lblMaximumElite;
    private javax.swing.JLabel lblMinimumRatio;
    private javax.swing.JLabel lblMinimumToSurvive;
    private javax.swing.JLabel lblMutationProp;
    private javax.swing.JLabel lblNormalize;
    private javax.swing.JLabel lblPopulationSize;
    // End of variables declaration//GEN-END:variables

}
