/*
 * WorldView.java
 *
 * Created on 30. jen 2007, 20:19
 */

package by.dak.cutting.cut.gui;

import by.dak.cutting.cut.genetics.Population;
import by.dak.cutting.cut.genetics.World;

import javax.swing.*;

//import by.dak.cutting.cut.gui.population.PopulationView;


/**
 * @author Peca
 */
public class WorldView extends javax.swing.JPanel
{

    private World world;
    //private PopulationView populationView;
    private boolean doStop;

    public WorldView(World world)
    {
        initComponents();
        this.world = world;
        // this.populationView = new PopulationView(null);
        // this.populationView.setSize(500, 200);
        //this.populationView.showBestIndividual();
        // this.jPanel1.add(this.populationView);
        this.update();
    }

    public synchronized void update()
    {
        populatePouplationsList();
        //this.populationView.update();
        jLabel1.setText(String.valueOf(this.world.currentPopulationIndex));
        jLabel3.setText(String.format("iteration: %d", this.world.getIteration()));
        listPopulations1.setSelectedIndex(this.world.currentPopulationIndex);
        if (this.world.getBestIndividual() != null)
            lblBestIndividual1.setText(this.world.getBestIndividual().getIndividualRating().toString());
    }

    private void populatePouplationsList()
    {
        DefaultListModel lm = new DefaultListModel();
        for (Population pop : world.getPopulations())
        {
            lm.addElement(pop);
        }
        //int index = listPopulations1.getSelectedIndex();
        listPopulations1.setModel(lm);
        //listPopulations1.setSelectedIndex(index);
    }

    class LoopThread extends Thread
    {
        LoopThread()
        {
        }

        public void run()
        {
            if (world == null) return;
            int cnt = 0;
            long t = System.currentTimeMillis();
            while (!doStop)
            {
                //world.nextGeneration();
                world.quickPass();
                /*if(bestIndividual != population.getBestIndividual()){
                    bestIndividual = population.getBestIndividual();
                    float f = ((Double)jSpinner1.getValue()).floatValue();
                    if(bestIndividual.getRating() >= f) doStop = true;
                    if(bestIndividualVisualizer != null){
                        bestIndividualVisualizer.setIndividual(bestIndividual);
                    }
                }
                if((cnt % 20) == 0) update();
                updateTitle();
                cnt++;*/
                if (System.currentTimeMillis() > t + 1000)
                {
                    update();
                    //populationView.update();
                    t = System.currentTimeMillis();
                }
            }
            update();
        }
    }


    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPopulations1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        btnMigrate1 = new javax.swing.JButton();
        btnNextGeneration1 = new javax.swing.JButton();
        btnLoop1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBestIndividual1 = new javax.swing.JLabel();
        btnQuickPass1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        listPopulations1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize()
            {
                return strings.length;
            }

            public Object getElementAt(int i)
            {
                return strings[i];
            }
        });
        listPopulations1.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                listPopulations1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPopulations1);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnMigrate1.setText("Migrate");
        btnMigrate1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnMigrate1MouseClicked(evt);
            }
        });

        btnNextGeneration1.setText("Next generation");
        btnNextGeneration1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnNextGeneration1MouseClicked(evt);
            }
        });

        btnLoop1.setText("Loop");
        btnLoop1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnLoop1MouseClicked(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("Best:");

        lblBestIndividual1.setText("jLabel3");

        btnQuickPass1.setText("Quick pass");
        btnQuickPass1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnQuickPass1MouseClicked(evt);
            }
        });

        jLabel3.setText("jLabel3");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(btnMigrate1)
                                                        .add(btnNextGeneration1)
                                                        .add(layout.createSequentialGroup()
                                                                .add(btnLoop1)
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                                .add(btnQuickPass1))
                                                        .add(jLabel1)
                                                        .add(layout.createSequentialGroup()
                                                                .add(jLabel2)
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(lblBestIndividual1))))
                                        .add(layout.createSequentialGroup()
                                                .add(24, 24, 24)
                                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(jLabel3)))
                                .add(18, 18, 18)
                                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(29, 29, 29)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 401, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(22, Short.MAX_VALUE))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(btnMigrate1)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(btnNextGeneration1)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                        .add(btnLoop1)
                                                        .add(btnQuickPass1))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jLabel1)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                        .add(jLabel2)
                                                        .add(lblBestIndividual1))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jLabel3)
                                                .add(20, 20, 20))))
        );
    }// </draw-fold>//GEN-END:initComponents

    private void listPopulations1ValueChanged(javax.swing.event.ListSelectionEvent evt)
    {//GEN-FIRST:event_listPopulations1ValueChanged
        Population pop = (Population) listPopulations1.getSelectedValue();
        // populationView.setPopulation(pop);
    }//GEN-LAST:event_listPopulations1ValueChanged

    private void btnMigrate1MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_btnMigrate1MouseClicked
        Population pop = (Population) listPopulations1.getSelectedValue();
        this.world.migrate(pop);
        update();
    }//GEN-LAST:event_btnMigrate1MouseClicked

    private void btnNextGeneration1MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_btnNextGeneration1MouseClicked
        this.world.nextGeneration();
        update();
    }//GEN-LAST:event_btnNextGeneration1MouseClicked

    private void btnLoop1MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_btnLoop1MouseClicked
        if (btnLoop1.getText().equals("Loop"))
        {
            btnLoop1.setText("Stop");
            doStop = false;
            LoopThread t = new LoopThread();
            t.setPriority(java.lang.Thread.MIN_PRIORITY);
            t.start();
        }
        else
        {
            doStop = true;
            btnLoop1.setText("Loop");
        }
    }//GEN-LAST:event_btnLoop1MouseClicked

    private void btnQuickPass1MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_btnQuickPass1MouseClicked
        this.world.quickPass();
        update();
    }//GEN-LAST:event_btnQuickPass1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoop1;
    private javax.swing.JButton btnMigrate1;
    private javax.swing.JButton btnNextGeneration1;
    private javax.swing.JButton btnQuickPass1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBestIndividual1;
    private javax.swing.JList listPopulations1;
    // End of variables declaration//GEN-END:variables

}
