/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogTest.java
 *
 * Created on 9.9.2009, 18.33.10
 */

package by.dak.cutting.doors.mech;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 * @author alkoyro
 */
public class DoorMechPanelT extends javax.swing.JDialog
{
//    ShapeDefImpl shapeDef;
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(by.dak.cutting.CuttingApp.class).getContext().getResourceMap(DoorMechPanel.class);
    /**
     * Creates new form DialogTest
     */
    public DoorMechPanelT(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        test();
        result();
    }

    private void result()
    {
        AbstractAction action = new AbstractAction()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {

//                System.out.println("Thickness"+doorMechPanel1.getShape().getMatThickness());
//                System.out.println("Code"+doorMechPanel1.getShape().getCode());
//                System.out.println("Width"+doorMechPanel1.getShape().getWidth());
//                System.out.println("Length"+doorMechPanel1.getShape().getLength());
//                System.out.println("Indent"+doorMechPanel1.getShape().getIndent());
            }
        };
        action.putValue(Action.NAME,resourceMap.getString("okButton.text"));
        doorMechPanel1.getOkButton().setAction(action);


    }

    private void test()
    {
//        if(shapeDef == null)
//        {
//            shapeDef = new ShapeDefImpl();
//            shapeDef.setCode("code1");
//            shapeDef.setIndent(new Integer(1));
//            shapeDef.setLength(new Long(1));
//            shapeDef.setMatThickness(new Integer(1));
//            shapeDef.setWidth(new Integer(1));
//        }
//        doorMechPanel1.setShape(shapeDef);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doorMechPanel1 = new by.dak.cutting.doors.mech.DoorMechPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        doorMechPanel1.setName("doorMechPanel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doorMechPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doorMechPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                DoorMechPanelT dialog = new DoorMechPanelT(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private by.dak.cutting.doors.mech.DoorMechPanel doorMechPanel1;
    // End of variables declaration//GEN-END:variables

}
