--ProfileCompDef
create table PROFILE_COMP_DEF (ID bigint generated by default as identity,
CODE varchar(255) not null,
MAT_THICKESS int not null,
WIDTH int not null,
LENGTH bigint not null,
INDENT int not null
);

--ProfileComp
create table PROFILE_COMP (ID bigint generated by default as identity,
LENGTH bigint not null
);

--ProfileDef
create table PROFILE_DEF (ID bigint generated by default as identity,
NAME varchar(255) not null,
unique(NAME)
);