--ZButtLink
ALTER table ORDER_DETAIL add SIDE VARCHAR(255);

--FURNITURE_TYPE_LINK
create table FURNITURE_TYPE_LINK (ID bigint generated by default as identity,
KEYWORD VARCHAR(255) not null,
PARENT_ID bigint not null,
CHILD_ID bigint not null,
constraint PK_FURNITURE_TYPE_LINK primary key (ID) ,
unique (KEYWORD, PARENT_ID, CHILD_ID)
);

alter table FURNITURE_TYPE_LINK add constraint PLINK_FURNITURE_TYPE foreign key (PARENT_ID) references FURNITURE_TYPE (ID) on delete cascade;
alter table FURNITURE_TYPE_LINK add constraint CLINK_FURNITURE_TYPE foreign key (CHILD_ID) references FURNITURE_TYPE (ID) on delete cascade;

UPDATE ORDER_DETAIL od set od.AMOUNT = 1 where od.DISCRIMINATOR = 'FurnitureLink';
UPDATE ORDER_DETAIL od set od.AMOUNT = 1 where od.DISCRIMINATOR = 'Additional';

-- устанавлеваем количество вместо размера
update ORDER_DETAIL set AMOUNT=SIZE,SIZE=1 where ID in(select OD.ID from ORDER_DETAIL OD
inner join FURNITURE_TYPE FT on FT.ID = OD.FURNITURE_TYPE_ID
where OD.DISCRIMINATOR = 'FurnitureLink'
and FT.UNIT = 'piece');

