/*
 * To change this template, choose Tools | Templates
 * and open the template in the draw.
 */

/*
 * BaseDirectoryDialog.java
 *
 * Created on 10.02.2009, 11:33:05
 */

package by.dak.cutting.swing;

import org.bushe.swing.event.annotation.AnnotationProcessor;

/**
 *
 * @author savage
 */
public abstract class BaseDirectoryDialog extends javax.swing.JDialog {
    public static enum EditType {
		FULL,ADD
	}
    public EditType editType = EditType.FULL;
    /**
     * @return the editType
     */
    public EditType getEditType() {
        return editType;
    }

    protected void initEnvironment(){
        setFocusable(true);
		getRootPane().setDefaultButton(buttonOK);
    }
    /**
     * @param editType the editType to set
     */
    public void setEditType(EditType editType) {
        this.editType = editType;
        if(editType.equals(EditType.ADD)){
            buttonDel.setVisible(false);
            buttonOpen.setVisible(false);
            frontTable.setMouseProcessed(false);
        }
    }
    /** Creates new form BaseDirectoryDialog */
    public BaseDirectoryDialog() {
        initComponents();
        initEnvironment();
    }
    public BaseDirectoryDialog(java.awt.Frame parent, boolean modal,EditType editType){
        super(parent,modal);
        initComponents();
        initEnvironment();
        setEditType(editType);
        AnnotationProcessor.process(this);
    }


    
    abstract protected void initBinding();
    abstract protected void onNew();
    abstract protected void onOpen();
    abstract protected void onDelete();
    abstract protected void updateGrid();
    abstract protected void onOk();


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOK = new javax.swing.JButton();
        frontTable = new by.dak.cutting.swing.NaviTable();
        jButton1 = new javax.swing.JButton();
        buttonOpen = new javax.swing.JButton();
        buttonDel = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(by.dak.cutting.CuttingApp.class).getContext().getResourceMap(BaseDirectoryDialog.class);
        buttonOK.setText(resourceMap.getString("buttonOK.text")); // NOI18N
        buttonOK.setName("buttonOK"); // NOI18N

        frontTable.setName("frontTable"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        buttonOpen.setText(resourceMap.getString("buttonOpen.text")); // NOI18N
        buttonOpen.setName("buttonOpen"); // NOI18N

        buttonDel.setText(resourceMap.getString("buttonDel.text")); // NOI18N
        buttonDel.setName("buttonDel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDel)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonOK)
                    .addComponent(frontTable, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frontTable, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonOpen)
                    .addComponent(buttonDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </draw-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton buttonDel;
    protected javax.swing.JButton buttonOK;
    protected javax.swing.JButton buttonOpen;
    protected by.dak.cutting.swing.NaviTable frontTable;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
