package by.dak.cutting.swing;

import javax.swing.*;

/**
 * @author Rudak Alexei
 */
public class BasePanel extends DPanel
{

    /**
     * Creates new form SVPanel
     */
    public BasePanel()
    {
        initComponents();
    }

    @Override
    public void setEnabled(boolean f)
    {
        traceComponents(this, f);
    }

    public void traceComponents(Object o, boolean f)
    {
        if (o instanceof JPanel)
        {
            JPanel temp = (JPanel) o;
            for (int a = 0; a < temp.getComponentCount(); a++)
            {
                Object obj = temp.getComponent(a);
                traceComponents(obj, f);
            }
        }
        else
        {
            JComponent c = (JComponent) o;
            c.setEnabled(f);
        }

    }

    public void setCaption(String text)
    {
        setBorder(BorderFactory.
                createTitledBorder(BorderFactory.createTitledBorder(text)));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(0, 300, Short.MAX_VALUE)
        );
    }// </draw-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
