package by.dak.cutting.swing;

import com.jgoodies.validation.ValidationResultModel;
import com.jgoodies.validation.util.DefaultValidationResultModel;
import com.jgoodies.validation.view.ValidationResultViewFactory;

import javax.swing.*;
import java.awt.*;

/**
 * Validation list control
 *
 * @author Rudak Alexei
 */
public class WarningList extends javax.swing.JPanel
{
    private JComponent validationResultsComponent;
    private ValidationResultModel validationResultModel =
            new DefaultValidationResultModel();

    /**
     * Creates new form SVWarningList
     */
    public WarningList()
    {
        initComponents();
    }

    public void initEnvironment()
    {
    }

    public ValidationResultModel getModel()
    {
        return validationResultModel;
    }

    public void setModel(ValidationResultModel validationResultModel)
    {
        this.validationResultModel = validationResultModel;
        validate();
        repaint();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <draw-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setLayout(new java.awt.BorderLayout());
        validationResultsComponent =
                ValidationResultViewFactory.createReportList(
                        this.validationResultModel);
        this.add(BorderLayout.CENTER, validationResultsComponent);

    }// </draw-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
