SELECT
     BORDER_DEF.NAME AS BORDER_DEF_NAME,
     BORDER_DEF.UNIT AS UNIT,
     TEXTURE.NAME AS TEXTURE_NAME,
     TEXTURE.CODE AS TEXTURE_CODE,
     MANUFACTURER.SHORT_NAME AS MANUFACTURER_SHORT_NAME,
     sum(FURNITURE.LENGTH * FURNITURE.AMOUNT)  AS LENGTH
FROM
    FURNITURE FURNITURE
     INNER JOIN PUBLIC.FURNITURE_CODE TEXTURE ON FURNITURE.FURNITURE_CODE_ID = TEXTURE.ID
     INNER JOIN PUBLIC.FURNITURE_TYPE BORDER_DEF ON FURNITURE.FURNITURE_TYPE_ID = BORDER_DEF.ID
     INNER JOIN PUBLIC.MANUFACTURER MANUFACTURER ON TEXTURE.MANUFACTURER_ID = MANUFACTURER.ID
     INNER JOIN PUBLIC.FURN_ORDER FURN_ORDER ON FURN_ORDER.ID = FURNITURE.ORDER_ID
WHERE
     FURNITURE.DISCRIMINATOR = 'Border' and
     FURNITURE.ORDER_ID is not null and
     FURN_ORDER.ORDER_GROUP_ID = $P{ORDER_GROUP_ID}
GROUP BY
     BORDER_DEF.NAME,
     MANUFACTURER.SHORT_NAME,
     TEXTURE.NAME,
     TEXTURE.CODE,
     BORDER_DEF.UNIT
ORDER BY
     BORDER_DEF.NAME ASC,
     MANUFACTURER.SHORT_NAME ASC,
     TEXTURE.NAME ASC



SELECT
     FURNITURE_TYPE.NAME AS FURNITURE_TYPE_NAME,
     FURNITURE_TYPE.UNIT AS UNIT,
     FURNITURE_CODE.NAME AS FURNITURE_CODE_NAME,
     FURNITURE_CODE.CODE AS FURNITURE_CODE_CODE,
     MANUFACTURER.SHORT_NAME AS MANUFACTURER_SHORT_NAME,
     FURNITURE.LENGTH AS LENGTH,
     FURNITURE.WIDTH AS WIDTH,
     sum(FURNITURE.AMOUNT)  AS AMOUNT
FROM
    FURNITURE FURNITURE
     INNER JOIN PUBLIC.FURNITURE_CODE FURNITURE_CODE ON FURNITURE.FURNITURE_CODE_ID = FURNITURE_CODE.ID
     INNER JOIN PUBLIC.FURNITURE_TYPE FURNITURE_TYPE ON FURNITURE.FURNITURE_TYPE_ID = FURNITURE_TYPE.ID
     INNER JOIN PUBLIC.MANUFACTURER MANUFACTURER ON FURNITURE_CODE.MANUFACTURER_ID = MANUFACTURER.ID
     INNER JOIN PUBLIC.FURN_ORDER FURN_ORDER ON FURN_ORDER.ID = FURNITURE.ORDER_ID
WHERE
     FURNITURE.DISCRIMINATOR = 'Board' and
     FURNITURE.ORDER_ID is not null and
     FURN_ORDER.ORDER_GROUP_ID = $P{ORDER_GROUP_ID}
GROUP BY
     FURNITURE_TYPE.NAME,
     MANUFACTURER.SHORT_NAME,
     FURNITURE_CODE.NAME,
     FURNITURE_CODE.CODE,
     FURNITURE.LENGTH,
     FURNITURE.WIDTH,
     FURNITURE_TYPE.UNIT
ORDER BY
     FURNITURE_TYPE.NAME ASC,
     MANUFACTURER.SHORT_NAME ASC,
     FURNITURE_CODE.NAME ASC


SELECT FURN_ORDER.ORDER_NUMBER, FURN_ORDER.NAME, DAILY_SHEET_C.DATE as CREATED_DATE, DAILY_SHEET_W.DATE as PRODUCTION_DATE,
FURN_ORDER.READY_DATE,CUSTOMER.NAME as CUSTOMER_NAME
FROM PUBLIC.FURN_ORDER FURN_ORDER
     INNER JOIN PUBLIC.DAILY_SHEET DAILY_SHEET_C ON FURN_ORDER.FK_CREATED_DAILY_SHEET_ID = DAILY_SHEET_C.ID
INNER JOIN PUBLIC.DAILY_SHEET DAILY_SHEET_W ON FURN_ORDER.FK_WORKED_DAILY_SHEET_ID = DAILY_SHEET_W.ID
INNER JOIN PUBLIC.CUSTOMER CUSTOMER ON FURN_ORDER.FK_CUSTOMER_ID = CUSTOMER.ID

WHERE
     FURN_ORDER.ORDER_GROUP_ID = $P{ORDER_GROUP_ID}
ORDER BY
     CUSTOMER.NAME,
     FURN_ORDER.FK_CREATED_DAILY_SHEET_ID,
     FURN_ORDER.FK_WORKED_DAILY_SHEET_ID,
     FURN_ORDER.READY_DATE


SELECT
     FURNITURE."SIZE" AS FURNITURE_SIZE,
     FURNITURE_TYPE."NAME" AS FURNITURE_TYPE_NAME,
     FURN_ORDER."NAME" AS FURN_ORDER_NAME,
     FURNITURE_CODE."NAME" AS FURNITURE_CODE_NAME,
     FURNITURE_CODE."CODE" AS FURNITURE_CODE_CODE,
     MANUFACTURER."SHORT_NAME" AS MANUFACTURER_SHORT_NAME,
     sum(FURNITURE."AMOUNT") AS FURNITURE_AMOUNT
FROM
     "PUBLIC"."FURNITURE" FURNITURE INNER JOIN "PUBLIC"."FURNITURE_CODE" FURNITURE_CODE ON FURNITURE."FURNITURE_CODE_ID" = FURNITURE_CODE."ID"
     INNER JOIN "PUBLIC"."FURNITURE_TYPE" FURNITURE_TYPE ON FURNITURE."FURNITURE_TYPE_ID" = FURNITURE_TYPE."ID"
     INNER JOIN "PUBLIC"."FURN_ORDER" FURN_ORDER ON FURNITURE."ORDER_ID" = FURN_ORDER."ID"
     INNER JOIN "PUBLIC"."ORDER_GROUP_LINK" ORDER_GROUP_LINK ON FURN_ORDER."ID" = ORDER_GROUP_LINK."ORDER_ID"
     INNER JOIN "PUBLIC"."MANUFACTURER" MANUFACTURER ON FURNITURE_CODE."MANUFACTURER_ID" = MANUFACTURER."ID"
WHERE
     ORDER_GROUP_LINK.GROUP_ID = $P{ORDER_GROUP_ID}
     AND FURNITURE_TYPE.UNIT = 'linearMetre'
     AND FURNITURE.ORDER_ID IS NOT null
GROUP BY
     FURNITURE."SIZE",
     FURNITURE_TYPE."NAME",
     MANUFACTURER."SHORT_NAME",
     FURNITURE_CODE."NAME",
     FURN_ORDER."NAME",
     FURNITURE_CODE."CODE",
     FURNITURE."AMOUNT"
ORDER BY
     FURNITURE_CODE."NAME" ASC,
     FURNITURE_TYPE."NAME" ASC